### PR TITLE
Add license specifications to package.xml

### PR DESCRIPTION
**Pull request by dbtucker**
Resolving issue https://github.com/mesosphere/universe/issues/523 for latest versions of package definition for Version 3.0.0 and 3.0.1 of the offering.

### CODE REVIEW

**Comment by ryadav88** [comment]
@dbtucker looks like it pulls 11 commits. for cleaner history, can we change the PR to pick the latest commit.

**Comment by dbtucker** [comment]
Is that doable on this PR, or should I cancel this one and create a new one with just that single commit ?

**Comment by ryadav88** [comment]
go ahead and cancel this one. A single commit would be ideal :)

**Comment by dbtucker** [comment]
Closing to resubmit with cleaner commit chain.

**Pull request closed without merging**
