### PR TITLE
Add new nginx package

### PR DESCRIPTION
**Pull request by ssk2**
This new package tweaks the wording, adds acceptedResourceRoles into the Marathon application definition (so the user is able to deploy to a public node), and removes the redundant marathon-uri parameter.

### CODE REVIEW

**Comment by ssk2** [comment]
@mohitsoni - I made a few tweaks to your package. Please have a look!

**Comment by kensipe** [comment]
@ssk2 could you rebase... otherwise LGTM

**Comment by kensipe** [comment]
LGTM

**Comment by mohitsoni** [comment]
@ssk2 Thanks for the PR. Having `acceptedResourceRoles` in there is a great idea.

**Pull request merged**
