### PR TITLE
Add new release of Vamp 0.9.2 to universe

### PR DESCRIPTION
**Pull request by iamtew**
Vamp 0.9.2 has been released, adding to Universe.

### CODE REVIEW

**Comment by ryadav88** [comment]
thanks @iamtew 
Can you review https://github.com/dcos/examples/tree/master/1.8/vamp and see if it needs any update? Feel free to submit a PR against that repo in case you want to add more details. This documentation will be available from DC/OS documentation site.

**Comment by iamtew** [comment]
hi @ryadav88 , the procedure hasn't changed so that document is still accurate.

**Comment by iamtew** [comment]
What is the current status of having this PR merged?

**Comment by iamtew** [comment]
Good catch, I missed that. 

New PR has been opened for examples: https://github.com/dcos/examples/pull/43

**Pull request merged**
