### PR TITLE
Updated Chronos 2.4.0 package.

### PR DESCRIPTION
**Pull request by gkleiman**
- Added new flags.
- Added default/minimum to all integer/number flags.
- Updated the Docker tag to the one corresponding to the final release of
  2.4.0, it was pointing to the RC1 before.

### CODE REVIEW

**Comment by kensipe** [comment]
on it!

**Comment by kensipe** [comment]
@gkleiman I notice a number of ports defined in the config (for instance the default cassandra port).  I wanted to make sure you realized that the frameworks team is looking to make this ports completely dynamic making it necessary for chrono to "discover" these ports.   You might want to make sure to add a task for that.

**Comment by kensipe** [comment]
LGTM... tests on dcos look good.  merging.

**Comment by gkleiman** [comment]
Thanks!

**Pull request merged**
