### PR TITLE
Add calico-dcos v3

### PR DESCRIPTION
**Pull request by djosborne**
Calico v3 introduces Calico v2.0 to DC/OS, running our latest platform release of calico services.

### CODE REVIEW

**Comment by ryadav88** [comment]
@djosborne Can I also ask you to write short `getting started` doc for this package so users don't have any issues installing and understanding how they work?

You can create a PR against https://github.com/dcos/examples and refer other examples listed there. These examples will finally go here: https://dcos.io/docs/1.8/usage/tutorials/.

This is also now part of the package submission guidelines: https://github.com/mesosphere/universe#submit-your-package

**Comment by fernandosanchezmunoz** [comment]
@djosborne @ryadav88 most of what's needed is already on Calico's documentation, so it should be mostly a format change. But some users have reported in the past issues with the installation process in your website, so this would be a good time to provide a tested&verified "from zero to hero" official installation process. I volunteer to provide a test cluster so that we can test this on a real setup and not on a Vagrant thingy. Ping me on email and let's make it happen.

**Comment by djosborne** [comment]
@ryadav88 @fernandosanchezmunoz We have a Calico-DC/OS install guide, but it's out of date / could use a revision. 

http://docs.projectcalico.org/v2.0/getting-started/mesos/installation/dc-os/framework

I'll clean it up and then ping you guys.

**Comment by djosborne** [comment]
@ryadav88 @fernandosanchezmunoz 
Here's the updated DC/OS Install Guide:
http://docs.projectcalico.org/v2.0/getting-started/mesos/installation/dc-os/framework

And the Installation Customization Guide:
http://docs.projectcalico.org/v2.0/getting-started/mesos/installation/dc-os/custom

**Comment by djosborne** [comment]
@ryadav88 @fernandosanchezmunoz ping

**Comment by ryadav88** [comment]
@djosborne I'll review it today.

**Comment by ryadav88** [comment]
> Here's the updated DC/OS Install Guide:
> http://docs.projectcalico.org/v2.0/getting-started/mesos/installation/dc-os/framework
> 
> And the Installation Customization Guide:
> http://docs.projectcalico.org/v2.0/getting-started/mesos/installation/dc-os/custom

@djosborne looks like this is still the old documentation based on version 0.3.1. Please update it to add steps for the latest version (how to access the service UI... ) and you can use the same content to create a PR against https://github.com/dcos/examples. By maintaining an example in that repo we can always make sure that updates to packages work with the new versions of dc/os and new users don't have problem understanding what the package is and how to install/run it. 

Apart from this, the PR LGTM. I would like to test the instructions in the `example` before merging this PR.

**Comment by djosborne** [comment]
@ryadav88 I updated the install images so they included the correct version string and show the new services UI. But I don't have the bandwidth to move the install docs to dcos/examples at the moment, as they'd also need some adjustments to fit that repository and link appropriately to the existing calico documentation.

Can we merge this update now and look to move that documentation in the future?

**Comment by djosborne** [comment]
@ryadav88 I updated the version string and services UI in the images.

I also copied our documentation and opened a PR here: https://github.com/dcos/examples/pull/45

**Pull request merged**
