### PR TITLE
Update Chronos, Marathon, and HDFS Packages

### PR DESCRIPTION
**Pull request by elingg**

### CODE REVIEW

**Comment by elingg** [comment]
Wait until https://github.com/mesosphere/universe/pull/140 is completed to merge (since the build will not pass). Please take a look @ConnorDoyle, @jsancio, @mgummelt

**Comment by elingg** [comment]
Also wait until https://github.com/mesosphere/universe/pull/141 is merged

**Comment by BenWhitehead** [comment]
@elingg please rebase this PR before merging, we don't want the extra merge message in the log.

**Comment by elingg** [comment]
@BenWhitehead, sure, any other comments?

**Comment by BenWhitehead** [comment]
As long as the build passes I think things are okay, we may want someone to review the wording of each of the steps.

**Comment by ConnorDoyle** [comment]
LGTM

**Pull request merged**
