### PR TITLE
Spark notebook

### PR DESCRIPTION
**Pull request by andypetrella**
Here is a fix for the spark notebook integration, we've made some test (including on enterprise edition of DC/OS).
We're on a blog to explain the how to

please @mhausenblas (or someone else if necessary, @stathy ?) can you have a look at that?

thanks a lot!

### CODE REVIEW

**Comment by mhausenblas** [comment]
@andypetrella can you pls fix this?

**Comment by andypetrella** [comment]
@mhausenblas I'm updating the branch, I guess this is skat you meant, am I right? Or did you encounter any issues?

**Comment by mhausenblas** [comment]
Please update again @andypetrella — many updates happening ATM :(

**Comment by mhausenblas** [comment]
Thanks @andypetrella!

**Pull request merged**
