### PR TITLE
Update chronos marathon.json with updated image

### PR DESCRIPTION
**Pull request by wallies**
Need this to work with latest mesos

### CODE REVIEW

**Comment by kensipe** [comment]
a version update like this would require a dcos version update... so this would increment chronos dcos version from 0 to 1.. and add an entry in the index.

Is that something you can add to this PR or should I create another and close this one?

**Comment by wallies** [comment]
i think i have done this correctly. Is there something I am missing?

**Comment by kensipe** [comment]
first glance it looks correct.  I'll comb thru and test now.

**Comment by kensipe** [comment]
and thx!

**Comment by kensipe** [comment]
LGTM and tested!  Thanks for the help!

**Pull request merged**
