### PR TITLE
Fix kubernetes license

### PR DESCRIPTION
**Pull request by mattj-io**

### CODE REVIEW

**Review by ryadav88 — APPROVED** [review]

**Review by MatApple — COMMENTED** [review]
This package is our own package and doesn't have base tech. Do we want to resolve to this license? https://raw.githubusercontent.com/kubernetes/kubernetes/master/LICENSE

The `kubernetes-cluster` package has the kubernetes base tech.

**Comment by mattj-io** [comment]
@MatApple - what's actually in this package ? Is this the framework code ? If so, that's proprietary and this PR isn't correct ..

**Comment by MatApple** [comment]
@mattj-io this package and our `kubernetes-cluster` packages are proprietary. This package contains only code we've written.

`kubernetes-cluster` package contains kubernetes code and code we've written to run it on DC/OS.

The code in both these packages is closed source.

**Comment by mattj-io** [comment]
@MatApple we still need to acknowledge the Apache licensed code for the portion we're redistributing. In the context of this exercise for Universe, it probably means listing both Apache and our proprietary license for the kubernetes-cluster package.

**Comment by MatApple** [comment]
That makes sense 👍 Thanks @mattj-io. I'll approve.

**Review by MatApple — APPROVED** [review]

**Comment by mattj-io** [comment]
I've added both Apache and proprietary to all of these packages, since I think kubernetes-cluster is pulled in by kubernetes, meaning it's deploying Apache code even if it doesn't contain it directly.

**Review by ryadav88 — APPROVED** [review]

**Pull request merged**
