### PR TITLE
spark fine grained mode

### PR DESCRIPTION
**Pull request by mgummelt**
Added a couple hacks to make spark work in fine-grained mode given the outstanding mesos bugs.

I added symlinks in the docker image to overcome the PATH bug
I added a conf/spark-env.sh entry to overcome the MESOS_NATIVE_JAVA_LIBRARY bug

### CODE REVIEW

**Comment by mgummelt** [comment]
cc @elingg

**Comment by gabrielhartmann** [comment]
Can you provide a link to the "outstanding mesos bug?"

**Comment by mgummelt** [comment]
https://issues.apache.org/jira/browse/MESOS-3866
https://issues.apache.org/jira/browse/MESOS-3836

**Comment by elingg** [comment]
LGTM so long as it was tested.

**Comment by keithchambers** [comment]
Shipped! Thanks @mgummelt!

**Pull request merged**
