### PR TITLE
Added Artifactory 5.3.1

### PR DESCRIPTION
**Pull request by jainishshah17**

### CODE REVIEW

**Comment by OhRobin** [comment]
@jainishshah17 I'm attempting to follow the installation example here https://github.com/dcos/examples/tree/master/artifactory/1.9 . It is rejecting my trial License Key. Any idea why?

**Comment by jainishshah17** [comment]
@OhRobin Can you provide me more information.

**Comment by OhRobin** [comment]
got a new license key thanks to @ryadav88 . The package looks good to me.

**Comment by jainishshah17** [comment]
@ryadav88 Can we have it merged?

**Pull request closed without merging**
