### PR TITLE
Added fixed version of Flink

### PR DESCRIPTION
**Pull request by joerg84**

### CODE REVIEW

**Comment by OhRobin** [comment]
the installation doesn't work right now because the janitor doesn't clean up flink properly from time to time. Will review again tomorrow.

**Comment by joerg84** [comment]
@OhRobin This is not a cleanup problem. Pushing a new version in a sec.

**Comment by joerg84** [comment]
Updated the docker image and have approvals for all upstream PRs leading into the changed docker  image. Tested on 1.9 and 1.10.

**Comment by fabianbaier** [comment]
Saw Joerg's fix working

**Pull request merged**
