### PR TITLE
Corrects the quobyte-server image name

### PR DESCRIPTION
**Pull request by casusbelli**
Fixes bug #392 in the Quobyte universe package.

### CODE REVIEW

**Comment by kensipe** [comment]
@casusbelli we don't allow fixes to versions like this without incrementing the index.  Specifically what I mean is these changes are in `repo/packages/Q/quobyte/0/` and that should be left in place.  Changes should result in `repo/packages/Q/quobyte/1/` 

I would be happy to help merge that in.

**Comment by casusbelli** [comment]
Ah, ok. Will update the PR later today. 
Thanks for the info!

**Comment by casusbelli** [comment]
@kensipe moved to new version directory (../1/..)

**Comment by casusbelli** [comment]
I moved this to a new PR: #414

**Pull request closed without merging**
