### PR TITLE
Update crate release to 0.2.1

### PR DESCRIPTION
**Pull request by aslanbekirov**

### CODE REVIEW

**Comment by ryadav88** [comment]
@aslanbekirov Are you still working on changes here or is this ready for review?

**Comment by ryadav88** [comment]
@aslanbekirov any update here?

**Comment by ryadav88** [comment]
closing out because of inactivity. 
let me know if this PR should be reopened again. 

cc / @joerg84

**Comment by joemoe** [comment]
hi @ryadav88,

aslan doesn't work at Crate anymore. We are not sure of the state of those changes if they still apply. Therefore it is okay for us to keep it closed. If we pick it up again we reopen this ticket or open a new one.

Cheers, Johannes

**Comment by ryadav88** [comment]
@joemoe sounds good. thanks for the update

**Pull request closed without merging**
