### PR TITLE
remove virtual ip labels

### PR DESCRIPTION
**Pull request by jfrazelle**

### CODE REVIEW

**Comment by kensipe** [comment]
@jfrazelle changes like this require a new index... (which are hard to diff, but are expected by cosmos).  so this change in `mysql/0` should result in a `mysql/`` with change.   don't forget to rerun the index scripts.

**Comment by jfrazelle** [comment]
hmm i did but maybe on an old checkout

**Comment by jfrazelle** [comment]
updated :)

**Comment by jfrazelle** [comment]
wow no sleep is killing me, now its good

**Comment by kensipe** [comment]
@jfrazelle perfect!

**Comment by kensipe** [comment]
this service fails to install

```

**Comment by jfrazelle** [comment]
ok we need to bump the memory for some reason on mine it doesnt need that much, will update thanks so much

**Comment by jfrazelle** [comment]
ok i have bumped to 512

**Comment by kensipe** [comment]
@jfrazelle I had the same failure... I bumped mem to 1024 and cpu to 1 and got it running.  I would add that the service doesn't recover well.  multiple attempts with failures resulted `/tmp/mysql` being established... then when a "good" config worked it failed because the dir existed.

Let me know what you want to do about the resource needs.  It isn't clear to me what the real needs of the service are.

**Comment by jfrazelle** [comment]
Hmmm ya it's not exactly clear to me either what the resource needs I upped the values though :/

**Comment by kensipe** [comment]
LGTM  merging!

**Comment by jfrazelle** [comment]
thanks!

**Pull request merged**
