### PR TITLE
Add beta-arangodb3

### PR DESCRIPTION
**Pull request by m0ppers**
commit 215cc472dd2af1a51b688e3bc0bcb3a94f098316
Merge: 5866047 1ef26f6
Author: Andreas Streichardt <andreas@arangodb.com>
Date:   Wed Jun 14 19:03:07 2017 +0200

    Merge https://github.com/mesosphere/universe into arangodb-3.2.x

commit 58660476b832dcf8bf0a105c55202e80de892376
Author: Andreas Streichardt <andreas@arangodb.com>
Date:   Wed Jun 14 19:01:51 2017 +0200

    Some polishing

commit 21e2e9b06c8803556b1b325a07fbdf7f026bede2
Author: Andreas Streichardt <andreas@arangodb.com>
Date:   Wed Jun 14 20:37:58 2017 +0200

    rename arangodb 3.2 project

commit 037bbee3598ffbca9fec63045acc529d5c9b584e
Author: Andreas Streichardt <andreas@arangodb.com>
Date:   Wed Jun 14 14:58:01 2017 +0200

    Add arangodb 3.2

### CODE REVIEW

**Comment by joerg84** [comment]
@ryadav88 We discussed a to have a beta package for arangoDB as well.

**Comment by ryadav88** [comment]
@m0ppers please rename the package to `arangodb3` and add this line in front of `preInstallNotes`: `This DC/OS Service is currently in preview. There may be bugs, incomplete features, incorrect documentation, or other discrepancies. Preview packages should never be used in production!`


Also, can you review https://github.com/dcos/examples/tree/master/arangodb/1.9 to see if there are any changed required in the documentation for this update.

**Comment by ryadav88** [comment]
@m0ppers any update here?

**Comment by joerg84** [comment]
Superceded by https://github.com/mesosphere/universe/pull/1283

**Pull request closed without merging**
