### PR TITLE
Bumping version number, various bugfixes and stability improvements

### PR DESCRIPTION
**Pull request by drewkerrigan**

### CODE REVIEW

**Comment by kensipe** [comment]
this looks good... let me give it a test.

**Comment by kensipe** [comment]
@drewkerrigan deploying the framework fails to launch.

Also the version update requires an update to the index file.  I was going to let it go and manage that in the merge however it looks like this version fails.

btw... after  you make an update like this, what I do is go to the scripts folder and run:

1. `./0-validate-version.sh `
2. `./1-validate-packages.sh `
3. `./2-build-index.sh `

which will validate the json files and update the index for you.

**Comment by drewkerrigan** [comment]
Oh ok, will do. Thanks!

**Comment by drewkerrigan** [comment]
@kensipe I ran:

```
dcos config set package.sources '["file:///Users/dkerrigan/src/mesosphere/universe"]'
dcos package update
dcos package install riak
dcos riak cluster create
dcos riak node add --nodes 2
dcos riak proxy install
```

I see no issues and the cluster seems to perform well. Do you have more context or error messages from when the framework failed to launch for you?

**Comment by drewkerrigan** [comment]
I should also note that file:///Users/dkerrigan/src/mesosphere/universe is indeed my ack-riak-mesos branch with the bumped version number.

**Comment by kensipe** [comment]
I'll give it another go

**Comment by kensipe** [comment]
tested good.... LGTM... merging!

**Pull request merged**
