### PR TITLE
Cluster status package

### PR DESCRIPTION
**Pull request by YuraTolochkevich**

### CODE REVIEW

**Comment by kensipe** [comment]
@YuraTolochkevich what is the status of this?  are you looking for a review?

**Comment by YuraTolochkevich** [comment]
@kensipe need to clarify @swartzrock

**Comment by swartzrock** [comment]
Michael, this was created for the DCOS Cluster command. Is this something you are already implementing?

**Comment by mgummelt** [comment]
I'm not aware of any `dcos cluster` command.  Do you mean the `dcos status` command we were talking about a couple weeks ago?

**Comment by BenWhitehead** [comment]
this should be rebased before any merge can take place.

**Comment by YuraTolochkevich** [comment]
@BenWhitehead Ready

**Comment by BenWhitehead** [comment]
I don't know the changes that are going into this such that I can review and merge, I was just commenting that the pr needed to be cleaned up before it could merge.

I'll let those who were reviewing previously do the merge.

**Pull request closed without merging**
