### PR TITLE
Fix command line opts

### PR DESCRIPTION
**Pull request by jgarcia-mesosphere**
Fixed command line opts.

### CODE REVIEW

**Comment by jgarcia-mesosphere** [comment]
@kensipe would you give this a peek pls?

**Comment by kensipe** [comment]
thanks @jgarcia-mesosphere I will take a look at this by tomorrow.  also... after the merge it is likely that I will remove this service from the universe and push it into the multiverse which is intended for incubating these kind of services.

**Comment by jgarcia-mesosphere** [comment]
@kensipe this def belongs in Multi until it stabilizes or maybe longer.

**Comment by elingg** [comment]
LGTM. Could you please put this PR in Multiverse, @jgarcia-mesosphere? Should be good to merge after Ken's changes in this PR, https://github.com/mesosphere/multiverse/pull/5, assuming you test against Multiverse.

**Comment by kensipe** [comment]
@jgarcia-mesosphere I tested this merged into version-1.x and ES still didn't work for me.  I'm moving ES to multiverse.  It would be very helpful if you could take a new look at it and send PR there.

thanks!

**Pull request closed without merging**
