### PR TITLE
Add airfield 0.2.0

### PR DESCRIPTION
**Pull request by swoehrl-mw**
New features:
* Secure airfield login with OpenID Connect (e.g. using keycloak)
* Preprovision new zeppelin instances with notebook templates
* Import and export notebooks
* Reconfigure notebooks after creation (with automatic export/import of notebooks)

Source: https://github.com/MaibornWolff/dcos-airfield/

### CODE REVIEW

**Review by vishnu2kmohan — APPROVED** [review]
All TeamCity tests have passed, thanks @swoehrl-mw!

**Review by ryadav88 — APPROVED** [review]

**Comment by ryadav88** [comment]
@swoehrl-mw is there a documentation example for this? https://github.com/dcos/examples

**Comment by swoehrl-mw** [comment]
@ryadav88 There is an existing example that I wrote for the first version: https://github.com/dcos/examples/tree/master/airfield/1.11
It is still valid for the new version.

**Comment by ryadav88** [comment]
great! thanks

**Pull request merged**
