### PR TITLE
gestalt-framework patch release 1.0.1

### PR DESCRIPTION
**Pull request by cgbaker**
- updated 1.0.0 release branch to 1.0.1
- added laser runtime enable flags

### CODE REVIEW

**Comment by cgbaker** [comment]
currently running at https://universe.galacticfog.com, tested with numerous installations over the past few weeks

**Comment by cgbaker** [comment]
Why?

**Comment by ryadav88** [comment]
@cgbaker Can I also ask you to write short getting started doc for the package so users don't have any issues installing and understanding how they work?

You can create a PR against https://github.com/dcos/examples and refer other examples listed there. These examples will finally go here: https://dcos.io/docs/1.8/usage/tutorials/.

This is also now part of the package submission guidelines: https://github.com/mesosphere/universe#submit-your-package

**Comment by cgbaker** [comment]
I'll add the getting started example now; I hadn't noticed that new requirement in the guidelines. Thank you.

**Comment by ryadav88** [comment]
@cgbaker any update here ?

**Comment by cgbaker** [comment]
I haven't heard back on my question about version shadowing using the same
directory.

**Comment by ryadav88** [comment]
@cgbaker ah I missed that! you can use directory version 2. that is fine.

**Comment by cgbaker** [comment]
Excellent, I'm waiting on our docs engineer to finish the write-up.

**Comment by cgbaker** [comment]
closing this in favor of a new PR

**Pull request closed without merging**
