### PR TITLE
change maintainer property

### PR DESCRIPTION
**Pull request by ryadav88**
Updated maintainer property from support@mesosphere.io to https://dcos.io/community
Haven't updated these packages: 
Kafka 
Cassandra 
Spark

Marathon 
Marathon-lb
tunnel-cli
Chronos
~~DSE~~
~~Exhibitor~~
Jenkins

@triclambert @keithchambers @ssk2 let me know if these should be changed too

### CODE REVIEW

**Comment by graham-murphy** [comment]
I'd remove Exhibitor and DSE as well, but looks good beyond that.

**Comment by triclambert** [comment]
Lgtm as long as @graham-murphy and @keithchambers are ok with it.

**Comment by triclambert** [comment]
@ssk2 the existing elastic packages are maintained by someone else entirely.  Our forthcoming new package should follow this community model initially.

**Comment by ryadav88** [comment]
looks like I got a quorum. @ssk2 can I ask you to merge it? dont want to merge my own PR.

**Comment by ssk2** [comment]
Woohoo, merge commit.

**Pull request merged**
