### PR TITLE
Retry NexCloud PR

### PR DESCRIPTION
**Pull request by nexclouding**
Nothing to revise

### CODE REVIEW

**Comment by nexclouding** [comment]
Can I ask why this checks fail happen over and over?

**Comment by ryadav88** [comment]
@takirala ^^

**Comment by takirala** [comment]
@ryadav88 it was an auth failure check. I triggered them again. I believe you should have access to click `Run` - _if_ you have access to view the teamcity CI.

**Comment by ryadav88** [comment]
@nexclouding one of the requirements of adding a package is creating a basic documentation example.To add the example, fork the https://github.com/dcos/examples repo and send in a pull request. You can re-use the format from the existing examples there.

**Review by ryadav88 — CHANGES_REQUESTED** [review]
add a documentation example

**Review by ryadav88 — APPROVED** [review]

**Pull request merged**
