### PR TITLE
Deprecate BeakerX package in favor of JupyterLab.

### PR DESCRIPTION
**Pull request by joerg84**

### CODE REVIEW

**Comment by joerg84** [comment]
ONLY MERGE after https://github.com/mesosphere/universe/pull/1895 is merged!

**Comment by fabianbaier** [comment]
lgtm

**Review by ryadav88 — APPROVED** [review]

**Review by fabianbaier — APPROVED** [review]
go for it

**Comment by joerg84** [comment]
Let us make sure we first update external references (e.g., blog posts)

**Pull request merged**
