### PR TITLE
Updated Jenkins Image with Mesos Scheduler

### PR DESCRIPTION
**Pull request by abhay-agarwal**

### CODE REVIEW

**Comment by abhay-agarwal** [comment]
@jsancio this is ready to merge :+1:

**Comment by jsancio** [comment]
Looks good to me. Squash commits and merge.

**Comment by abhay-agarwal** [comment]
Will merge once it's been tested extensively by the team.

**Comment by jsancio** [comment]
@abhay-agarwal Looks like we need a rebase.

**Comment by abhay-agarwal** [comment]
Just did. When this finishes, feel free to :shipit:

**Pull request merged**
