### PR TITLE
Update spark config defaults

### PR DESCRIPTION
**Pull request by adam-mesos**
@tnachen PTAL and confirm formatting for the defaults (then merge!)

### CODE REVIEW

**Comment by elingg** [comment]
:+1:

**Comment by ConnorDoyle** [comment]
Please run `scripts/build.sh` to keep the index up to date.

**Comment by adam-mesos** [comment]
@ConnorDoyle I did, but it didn't change anything. There weren't any required configs yet anyway, so maybe the index stayed the same?

**Comment by tnachen** [comment]
@adam-mesos Hey sorry didn't see this PR. I already did the change and merged it. It did rebuilt the index for me. I'm closing this PR.

**Pull request closed without merging**
