### PR TITLE
Official K8s icons

### PR DESCRIPTION
**Pull request by abhay-agarwal**
Small change that was annoying me.

### CODE REVIEW

**Comment by cmaloney** [comment]
Why are we changing the url here? downloads.mesosphere.com is setup so that things will leave the cache over time automatically.

**Comment by abhay-agarwal** [comment]
This is more transparent than me changing random s3 files.

**Comment by cmaloney** [comment]
Not particularly... I have no idea what the old vs. new is, they still could change without warning / notice.

The only way this would get particularly transparent is if the icons live inside the git repository and are automatically updated / deployed on commit (Or are grabbed from github directly)

**Comment by abhay-agarwal** [comment]
Okay i'll change them then.

**Comment by jdef** [comment]
There is a build job in TC that uploads icons from the kubernetes-mesos
github repo.

**Comment by abhay-agarwal** [comment]
Our UI team has official icons that don't have the ugly black background and scale better to retina screens. I'm not sure why there needs to be that degree of automation to create a team city job but whatever makes people happy. I'll stay out of it.

**Comment by jdef** [comment]
we don't need that level of automation. and I like the new icons. i only
mentioned the automation because i don't have direct access to the s3
bucket and the only way for me to get icons up there was via the build
process, as recommended by cody, et al.

**Pull request closed without merging**
