### PR TITLE
added latest stable marathon release v0.10.1

### PR DESCRIPTION
**Pull request by meichstedt**
Adds the latest stable marathon release [v0.10.1](https://github.com/mesosphere/marathon/releases/tag/v0.10.1) with updated CLI flags.

_Note: should the `repo/meta/index.json.gz` be added to `.gitignore`, or is it OK to have it version controlled?_

### CODE REVIEW

**Comment by meichstedt** [comment]
@kensipe Could you have a look?

**Comment by kensipe** [comment]
@meichstedt looking

**Comment by kensipe** [comment]
and `index.json.gz` I believe is a necessary component.. unfortunately

**Comment by kensipe** [comment]
LGTM!

**Pull request merged**
