### PR TITLE
removed framework-name

### PR DESCRIPTION
**Pull request by kensipe**
fixes: https://mesosphere.atlassian.net/browse/CASSANDRA-330

### CODE REVIEW

**Comment by gabrielhartmann** [comment]
@kensipe:  Talk to @mgummelt and @rcorral to figure out what to do here.  I thought were were going with service.id.  Is framework-name ready to be removed?

**Comment by mgummelt** [comment]
Just talked to @rcorral.  They're implementing support for `service.name` ~tomorrow

**Comment by pyronicide** [comment]
@kensipe: please fix the conflicts.

**Comment by keithchambers** [comment]
I believe @kow3ns made updates that supersede this PR in the 1-7ea branch.

@kow3ns @kensipe can we delete this PR?

**Pull request closed without merging**
