### PR TITLE
adding the dcos service labels for chronos

### PR DESCRIPTION
**Pull request by kensipe**

### CODE REVIEW

**Comment by kensipe** [comment]
This is an exact copy of the /0 index adding the dcos labels for chronos.   No other changes introduced.

**Comment by jdef** [comment]
What about the other DCOS_ labels that, for example, Jenkins has defined?
https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/J/jenkins/11/marathon.json.mustache#L70

**Comment by kensipe** [comment]
@jdef I was so confused by your message... until I realized that the labels I added were not even pushed... crazy.  fixed.

**Comment by kensipe** [comment]
that was the full intent of this PR

**Comment by jdef** [comment]
lgtm

**Pull request merged**
