### PR TITLE
spark 1.5.0 with patch for multiple roles

### PR DESCRIPTION
**Pull request by mgummelt**
This is a build of this commit: https://github.com/mesosphere/spark/commit/db83ac7246ed6fd183974eaf412847ac0c26b1ea , which is @tnachen's multi role fix cherry-picked onto 1.5.0

I've only tested it against our basic test suite, not against anything testing the specific fix.  @tnachen says he means to write a unit test, but we don't have that yet.

### CODE REVIEW

**Comment by elingg** [comment]
The build needs to pass. We need to update repo/meta/index.json with the corresponding version. Sanity tests are okay for now, but if you can try writing a unit test or integration test  of @tnachen that will be a helpful learning experience and will give us more confidence. Testing multiple roles on a cluster would be another option.

**Comment by mgummelt** [comment]
Ran scripts/build.sh.  Tests are passing now.

I'll plan on leaving this here, and writing a test for roles after I set up the spark automated build.  If you want to give cisco this build before that, let me know and I'll push.

**Comment by elingg** [comment]
@mgummelt Another thing I thought of is that we want to have a level of confidence before going back to our customers so it will probably make the most sense to test this out before merge.

**Comment by kensipe** [comment]
@mgummelt do you need another tester on this?

**Comment by mgummelt** [comment]
tim said he would write the unit tests today, so hopefully not

**Comment by elingg** [comment]
The build is still failing on this, see https://teamcity.mesosphere.io/viewLog.html?buildId=60245&buildTypeId=Oss_Universe_Ci&tab=buildLog#_focus=202. It shows a problem with the index. Could you try running scripts/build.sh? @mgummelt, the highest priority right now should be testing this to send it to Cisco before we create an automated build. @kensipe or @gabrielhartmann, that would be great if you can jump in and help with the testing here. I will see if I can take a look as well if there is time on Monday. Thanks!

**Comment by mgummelt** [comment]
@elingg @gabrielhartmann plz review

I've tested this against a raw mesos cluster to validate the fix described here: https://github.com/apache/spark/pull/8872

I've also run dcos-tests against a DCOS cluster.

**Comment by elingg** [comment]
LGTM @mgummelt. If no objections soon from @gabrielhartmann, let's merge!

**Pull request merged**
