### PR TITLE
New version of Datadog package to monitor Mesos

### PR DESCRIPTION
**Pull request by hkaj**
This new package is an update to the already existing [Datadog package](https://github.com/mesosphere/universe/tree/version-3.x/repo/packages/D/datadog/0). It upgrades to the latest version of our agent, uses `packagingVersion: 3.0` and collects more metrics.

### CODE REVIEW

**Comment by Bowbaq** [comment]
I'm interested in integrating DC/OS & Datadog, what's the status of this? What's the recommended setup to get metrics from all the agents *and* all the masters? Does this collect metrics for application containers running inside Marathon?

**Comment by irabinovitch** [comment]
@Bowbaq Once this PR is merged you will be able to install  Datadog like any other application from Universe.   It will monitor your mesos masters, slaves, and ZK instances.  It will also pull metrics from the underlying containers.  If you want to monitor your applications you might consider looking at Datadog's [service discovery](https://www.datadoghq.com/blog/service-discovery-monitoring-docker-containers-move/) feature which will allow you to specify custom monitors for classes of images.

**Comment by Bowbaq** [comment]
This doesn't appear to be working :/ Maybe I misconfigured something?

<details>
<summary>Marathon config</summary>
```
{
  "id": "/datadog",
  "cmd": null,
  "cpus": 0.05,
  "mem": 128,
  "disk": 0,
  "instances": 6,
  "constraints": [
    [
      "hostname",
      "UNIQUE"
    ],
    [
      "hostname",
      "GROUP_BY"
    ]
  ],
  "acceptedResourceRoles": [
    "slave_public",
    "*"
  ],
  "container": {
    "type": "DOCKER",
    "volumes": [
      {
        "containerPath": "/var/run/docker.sock",
        "hostPath": "/var/run/docker.sock",
        "mode": "RW"
      },
      {
        "containerPath": "/host/proc",
        "hostPath": "/proc",
        "mode": "RO"
      },
      {
        "containerPath": "/host/sys/fs/cgroup",
        "hostPath": "/sys/fs/cgroup",
        "mode": "RO"
      }
    ],
    "docker": {
      "image": "datadog/docker-dd-agent:11.2.583",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 8125,
          "hostPort": 8125,
          "servicePort": 10000,
          "protocol": "udp",
          "labels": {}
        },
        {
          "containerPort": 9001,
          "hostPort": 9001,
          "servicePort": 10001,
          "protocol": "tcp",
          "labels": {}
        }
      ],
      "privileged": false,
      "parameters": [
        {
          "key": "name",
          "value": "dd-agent"
        },
        {
          "key": "env",
          "value": "API_KEY=******************"
        },
        {
          "key": "env",
          "value": "MESOS_SLAVE=true"
        }
      ],
      "forcePullImage": false
    }
  },
  "healthChecks": [
    {
      "path": "/",
      "protocol": "HTTP",
      "portIndex": 1,
      "gracePeriodSeconds": 300,
      "intervalSeconds": 60,
      "timeoutSeconds": 20,
      "maxConsecutiveFailures": 3,
      "ignoreHttp1xx": false
    }
  ],
  "labels": {
    "DCOS_PACKAGE_RELEASE": "1",
    "DCOS_PACKAGE_SOURCE": "https://universe.mesosphere.com/repo-1.7",
    "DCOS_PACKAGE_METADATA": "eyJsaWNlbnNlcyI6W3sibmFtZSI6IlNpbXBsaWZpZWQgQlNEIGxpY2Vuc2UiLCJ1cmwiOiJodHRwczovL3Jhdy5naXRodWJ1c2VyY29udGVudC5jb20vRGF0YURvZy9kZC1hZ2VudC9tYXN0ZXIvTElDRU5TRSJ9XSwid2Vic2l0ZSI6Imh0dHA6Ly93d3cuZGF0YWRvZy5jb20iLCJuYW1lIjoiZGF0YWRvZyIsInBvc3RJbnN0YWxsTm90ZXMiOiJEYXRhZG9nIG9uIERDT1Mgc3VjY2Vzc2Z1bGx5IGluc3RhbGxlZC5cbkhlYWQgb3ZlciB0byBodHRwczovL2FwcC5kYXRhZG9naHEuY29tIHRvIG1vbml0b3IgeW91ciBEQ09TIGNsdXN0ZXIuIiwic2NtIjoiaHR0cHM6Ly9naXRodWIuY29tL2RhdGFkb2cvZGQtYWdlbnQuZ2l0IiwiZGVzY3JpcHRpb24iOiJDbG91ZC1zY2FsZSBtb25pdG9yaW5nIiwicGFja2FnaW5nVmVyc2lvbiI6IjIuMCIsInRhZ3MiOlsiZGF0YWRvZyIsIm1vbml0b3JpbmciXSwicG9zdFVuaW5zdGFsbE5vdGVzIjoiRGF0YWRvZyBvbiBEQ09TIHN1Y2Nlc3NmdWxseSB1bmluc3RhbGxlZC5cbi4iLCJtYWludGFpbmVyIjoicGFja2FnZUBkYXRhZG9naHEuY29tIiwiZnJhbWV3b3JrIjpmYWxzZSwidmVyc2lvbiI6IjUuOC4zIiwicHJlSW5zdGFsbE5vdGVzIjoiUGFzcyB5b3VyIEFQSSBrZXkgYXMgYSBwYWNrYWdlIG9wdGlvbiAoZGF0YWRvZy5hcGlfa2V5KS5cbkFsc28gcGFzcyB0aGUgbnVtYmVyIG9mIE1lc29zIHNsYXZlcyBhcyBhbiBvcHRpb24gKGRhdGFkb2cuaW5zdGFuY2VzKS5cbk1hcmF0aG9uIHdpbGwgbWFrZSBzdXJlIHRoYXQgdGhlIERhdGFkb2cgQWdlbnQgcnVucyBvbmx5IG9uY2UgcGVyIHNsYXZlLiIsImltYWdlcyI6eyJpY29uLXNtYWxsIjoiaHR0cHM6Ly9kb3dubG9hZHMubWVzb3NwaGVyZS5jb20vdW5pdmVyc2UvYXNzZXRzL2ljb24tc2VydmljZS1kYXRhZG9nLXNtYWxsLnBuZyIsImljb24tbWVkaXVtIjoiaHR0cHM6Ly9kb3dubG9hZHMubWVzb3NwaGVyZS5jb20vdW5pdmVyc2UvYXNzZXRzL2ljb24tc2VydmljZS1kYXRhZG9nLW1lZGl1bS5wbmciLCJpY29uLWxhcmdlIjoiaHR0cHM6Ly9kb3dubG9hZHMubWVzb3NwaGVyZS5jb20vdW5pdmVyc2UvYXNzZXRzL2ljb24tc2VydmljZS1kYXRhZG9nLWxhcmdlLnBuZyIsInNjcmVlbnNob3RzIjpudWxsfX0=",
    "DCOS_PACKAGE_REGISTRY_VERSION": "2.0",
    "DCOS_PACKAGE_VERSION": "5.8.3",
    "DCOS_PACKAGE_NAME": "datadog",
    "DCOS_PACKAGE_IS_FRAMEWORK": "false"
  },
  "portDefinitions": [
    {
      "port": 10000,
      "protocol": "tcp",
      "labels": {}
    },
    {
      "port": 10001,
      "protocol": "tcp",
      "labels": {}
    }
  ]
}
```
</details>

<details>
<summary>Logs</summary>
```
-> % envs/dev/dcos task log datadog
===> task:datadog.1f6695b0-491b-11e6-8f16-9232fba66f34:stdout <===
2016-07-13 16:59:14,266 INFO spawned: 'forwarder' with pid 21
2016-07-13 16:59:14,269 INFO spawned: 'collector' with pid 22
2016-07-13 16:59:14,271 INFO spawned: 'jmxfetch' with pid 24
2016-07-13 16:59:16,954 INFO success: go-metro entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2016-07-13 16:59:17,956 INFO success: jmxfetch entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2016-07-13 16:59:18,734 INFO exited: jmxfetch (exit status 0; expected)
2016-07-13 16:59:19,393 INFO success: dogstatsd entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,393 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,393 INFO success: collector entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,544 INFO exited: go-metro (exit status 0; expected)
===> task:datadog.1f666e9f-491b-11e6-8f16-9232fba66f34:stdout <===
2016-07-13 16:59:14,254 INFO spawned: 'forwarder' with pid 21
2016-07-13 16:59:14,255 INFO spawned: 'collector' with pid 22
2016-07-13 16:59:14,257 INFO spawned: 'jmxfetch' with pid 23
2016-07-13 16:59:16,933 INFO success: go-metro entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2016-07-13 16:59:17,934 INFO success: jmxfetch entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2016-07-13 16:59:18,710 INFO exited: jmxfetch (exit status 0; expected)
2016-07-13 16:59:19,369 INFO success: dogstatsd entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,369 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,369 INFO success: collector entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,529 INFO exited: go-metro (exit status 0; expected)
===> task:datadog.1f65f96d-491b-11e6-8f16-9232fba66f34:stdout <===
2016-07-13 16:59:14,207 INFO spawned: 'forwarder' with pid 20
2016-07-13 16:59:14,208 INFO spawned: 'collector' with pid 21
2016-07-13 16:59:14,210 INFO spawned: 'jmxfetch' with pid 22
2016-07-13 16:59:16,949 INFO success: go-metro entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2016-07-13 16:59:17,950 INFO success: jmxfetch entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2016-07-13 16:59:18,686 INFO exited: jmxfetch (exit status 0; expected)
2016-07-13 16:59:19,381 INFO success: dogstatsd entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,382 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,382 INFO success: collector entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,587 INFO exited: go-metro (exit status 0; expected)
===> task:datadog.1f655d2b-491b-11e6-8f16-9232fba66f34:stdout <===
2016-07-13 16:59:14,224 INFO spawned: 'forwarder' with pid 20
2016-07-13 16:59:14,226 INFO spawned: 'collector' with pid 21
2016-07-13 16:59:14,227 INFO spawned: 'jmxfetch' with pid 22
2016-07-13 16:59:16,912 INFO success: go-metro entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2016-07-13 16:59:17,914 INFO success: jmxfetch entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2016-07-13 16:59:18,692 INFO exited: jmxfetch (exit status 0; expected)
2016-07-13 16:59:19,344 INFO success: dogstatsd entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,345 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,345 INFO success: collector entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,625 INFO exited: go-metro (exit status 0; expected)
===> task:datadog.1f65d25c-491b-11e6-8f16-9232fba66f34:stdout <===
2016-07-13 16:59:14,271 INFO spawned: 'forwarder' with pid 20
2016-07-13 16:59:14,273 INFO spawned: 'collector' with pid 21
2016-07-13 16:59:14,274 INFO spawned: 'jmxfetch' with pid 22
2016-07-13 16:59:16,973 INFO success: go-metro entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2016-07-13 16:59:17,974 INFO success: jmxfetch entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2016-07-13 16:59:18,736 INFO exited: jmxfetch (exit status 0; expected)
2016-07-13 16:59:19,415 INFO success: dogstatsd entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,415 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,415 INFO success: collector entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,646 INFO exited: go-metro (exit status 0; expected)
===> task:datadog.1f66207e-491b-11e6-8f16-9232fba66f34:stdout <===
2016-07-13 16:59:14,255 INFO spawned: 'forwarder' with pid 20
2016-07-13 16:59:14,256 INFO spawned: 'collector' with pid 21
2016-07-13 16:59:14,258 INFO spawned: 'jmxfetch' with pid 22
2016-07-13 16:59:16,987 INFO success: go-metro entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2016-07-13 16:59:17,989 INFO success: jmxfetch entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
2016-07-13 16:59:18,728 INFO exited: jmxfetch (exit status 0; expected)
2016-07-13 16:59:19,428 INFO success: dogstatsd entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,429 INFO success: forwarder entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,429 INFO success: collector entered RUNNING state, process has stayed up for > than 5 seconds (startsecs)
2016-07-13 16:59:19,603 INFO exited: go-metro (exit status 0; expected)
```
</details>

screenshot 2016-07-13 10 30 44

**Comment by hkaj** [comment]
Hi @Bowbaq

Can you [send a flare to Datadog](https://help.datadoghq.com/hc/en-us/articles/204991415-Send-logs-and-configs-to-Datadog-via-flare-command) from one of the datadog agent container running on Mesos please? It will contain more logs and help us investigate. Also are you running the master check somewhere or only the slave one? The Datadog package here only runs the slave check to avoid having all slave nodes query the master for the same metrics.
Most of the metrics on the graph in your screenshot are coming from the master check so that would explain part of the problem.

**Comment by Bowbaq** [comment]
Hi @hkaj,

I believe I've found the root cause for this. This [line](https://github.com/DataDog/docker-dd-agent/blob/master/entrypoint.sh#L108) grabs the hostname of the machine which on my setup doesn't (yet) resolve to the IP of the host. I've switched it to use `$HOST` in a custom docker image, which is set correctly.

I've been going back & forth w/ support (case #59243) on some details around running the master checks / marathon checks / getting host metrics

**Comment by hkaj** [comment]
I see, thank you @Bowbaq for investigating this.

What do you think would be the best way to get the box internal IP from the entrypoint in your setup?
My guess would be to use the default gateway of the container, it works "most of the time".
Would that work in your case? The agent will have to use a mix of both ways as in some cases this default gateway is hijacked by network overlay software, but if that works I'll issue a fix rapidly.

Do you mind testing it? I don't have the same setup as you, and it resolves correctly in my case.
You will need to open a shell into the agent container (`docker exec -it agent_container_name sh` as I think you're using the alpine-based image), install curl (`apk add curl`) and curl a mesos slave endpoint with the default gateway. Something like `curl http://$(ip route | grep default | cut -d' ' -f3):5051/state.json​` should do the trick.

Thanks again!

**Comment by pyronicide** [comment]
@hkaj you might want to use `MESOS_IP_DISCOVERY_COMMAND` (from `/opt/mesosphere/environment`). We use that for getting the correct internal IP on every host.

**Comment by Bowbaq** [comment]
@pyronicide this is from inside a docker container, so I'm not sure how that would work. In the container, both `HOST` and `LIBPROCESS_IP` appear to have the right value.

**Comment by mastrolinux** [comment]
be aware that dashboard is available only if you have `MESOS_MASTER=true` as a variable otherwise you will not see data there. @Bowbaq

**Comment by hkaj** [comment]
thanks for chiming in @mastrolinux 

Indeed most of this dashboard metrics come from the mesos master check (the Datadog agent run a different check on the master and slave nodes). Since master nodes are not "schedulable" in DC/OS this default dashboard looks empty if you don't run an agent with the `MESOS_MASTER=true` on the master(s) manually.

This needs to be more explicit though and we will document it better, with the preferred way to monitor master nodes as well.

**Pull request merged**
