### PR TITLE
httpd package

### PR DESCRIPTION
**Pull request by Abhijeet-Jadhav**
Addition of httpd package to universe

### CODE REVIEW

**Comment by BenWhitehead** [comment]
Hi @Abhijeet-Jadhav I'll look into why the third build is failing and report back.

**Comment by BenWhitehead** [comment]
I've identified the bug in the validation code, I'll try and get a new built soon with the bugfix.

**Comment by BenWhitehead** [comment]
@Abhijeet-Jadhav the bug in the validation code has been fixed. Apologies.

**Comment by cruhland** [comment]
@spahl, this is blocked by https://github.com/dcos/dcos/pull/528

**Comment by BenWhitehead** [comment]
@Abhijeet-Jadhav Actually, after thinking more about the fix to the validation code, the validation code was inline with what is expected for dcos 1.7 and older.

So if you want your package to work for versions of DC/OS 1.7 or older you will need to provide values for all three image icons.

If instead you only want your package to work for DC/OS 1.8 or newer you can set `minDcosReleaseVersion` in your package.json to 1.8 and keep what is defined here.  I'm going to see if I can update the validation code to make this circumstance more clear if it happens again.

Sorry for any confusion.

**Comment by BenWhitehead** [comment]
@spahl this is actually blocked until my above comment is addressed.

**Comment by BenWhitehead** [comment]
@Abhijeet-Jadhav I've update the validation code to enforce the nuance I've called out above, so when the build turns green this should be okay to merge.  Feel free to ping me on this thread if you run into issues or need clarification of the above.

**Comment by Abhijeet-Jadhav** [comment]
Hi @BenWhitehead, i wasn't able to push to this branch. So i created another branch and pushed to that one ( https://github.com/mesosphere/universe/pull/644 ). The third check is still failing even after i provided values for all 3 image icons.

**Comment by BenWhitehead** [comment]
@Abhijeet-Jadhav I commented on the other PR, going to close this one.

**Pull request closed without merging**
