### PR TITLE
reduce default memory required for jenkins

### PR DESCRIPTION
**Pull request by rji**
This commit reduces the default (minimum) amount of memory for the
Jenkins service from 2 GB to 1 GB, and modifies the JVM heap size from
1024m to 512m.

### CODE REVIEW

**Comment by jsancio** [comment]
@rji Let's create a new package revision. Technically, package are immutable.

**Comment by ssk2** [comment]
@jsancio - but this commit didn't create new packages - https://github.com/mesosphere/universe/pull/354/files

**Comment by jsancio** [comment]
Rules are meant to be broken.

**Comment by rji** [comment]
Updated PR to make this change in a new package revision.

**Pull request merged**
