### PR TITLE
updated grafana to use the newest version 4.2.0

### PR DESCRIPTION
**Pull request by lockwobr**
I updated grafana package to use the newest version, I have been testing this version in dcos 1.9 and work better then 3.1.1 version. Was not 100 sure if i setup the new version write with the directory, let me know if it is not correct or if i need to do more to contribute this new version.

### CODE REVIEW

**Comment by fernandosanchezmunoz** [comment]
@lockwobr thanks for the PR!! Can you please bump the version to 4.2.0:0.2 to reflect the package change? Also, can you please add the new screenshots to the tutorial in https://github.com/dcos/examples/tree/master/cadvisor-influxdb-grafana (if you're running 1.9 already just add the tutorial for 1.9 directly with the new screenshots -- I'll update 1.8 afterwards). 
Other than that LGTM-- tested and working!  Thanks!!

**Comment by lockwobr** [comment]
@fernandosanchezmunoz I dont have an env anymore to get screen shots, but i did bump the version number.

**Comment by fernandosanchezmunoz** [comment]
@ryadav88 this is tested and working. Let me know your thoughts on pushing without updating the tutorial. I don't have the bandwidth just now so if you want to take that one go ahead.

**Comment by fernandosanchezmunoz** [comment]
@lockwobr can you please bump the package version in the Marathon app definition too please.

**Comment by ryadav88** [comment]
@fernandosanchezmunoz we have an open PR  : https://github.com/dcos/examples/pull/136

**Comment by lockwobr** [comment]
@fernandosanchezmunoz I can hard code like 
`"DCOS_PACKAGE_VERSION": "4.2.0-0.2",`
or can ? or should do it so it pulls from the package.json like
`"DCOS_PACKAGE_VERSION": "{{package.version}}",`

**Comment by fernandosanchezmunoz** [comment]
Well to be honest I haven't tried the second form and I'm not sure it would
work. The first one would work for sure. If you can try the second and
check in Marathon that it actually works, then it'd be even better.

thanks!

2017-04-25 13:29 GMT-04:00 Brian Lockwood <notifications@github.com>:

**Comment by lockwobr** [comment]
@fernandosanchezmunoz I don't have a place to test it, and looking at the other packages none of them have it that way so it might not work, and since can't test this change, went with the safe route.

**Comment by fernandosanchezmunoz** [comment]
LGTM

**Pull request merged**
