### PR TITLE
Bump Weave Scope version to 0.15

### PR DESCRIPTION
**Pull request by errordeveloper**
Update to latest version of Weave Scope.

### CODE REVIEW

**Comment by errordeveloper** [comment]
@pyronicide I've rebased this now, but I really didn't expect version bump PR to wait for so long...

**Comment by pyronicide** [comment]
@errordeveloper holy hell ... how did this sit so long. This is totally my fail.

**Comment by errordeveloper** [comment]
Thomas, we have 0.15 out now, probably better to get it in instead.

**Comment by pyronicide** [comment]
@errordeveloper would you like to update to `0.15`?

**Comment by errordeveloper** [comment]
@pyronicide I've updated it to 0.15 now.

**Comment by errordeveloper** [comment]
@pyronicide fantastic, thank you!

**Comment by pyronicide** [comment]
@errordeveloper of course! Thanks for being so patient, we'll get it way faster next time.

**Pull request merged**
