### PR TITLE
[SPARK-189] Spark CLI 0.5.4

### PR DESCRIPTION
**Pull request by mgummelt**
@gabrielhartmann plz review

### CODE REVIEW

**Comment by gabrielhartmann** [comment]
@mgummelt:  Can you give a quick summary of what this is accomplishing?  I assume this is fixing the auth problem.

**Comment by mgummelt** [comment]
No, auth problem was fixed in the previous version.  This includes this bugfix: https://github.com/mesosphere/dcos-spark/pull/22

**Comment by mgummelt** [comment]
Also, follow the JIRA pointer for more info

**Comment by gabrielhartmann** [comment]
@mgummelt:  Ok looks like the only thing that changed was the pointer to the download location for the cli.

**Comment by mgummelt** [comment]
@surdy Fixed.

**Comment by surdy** [comment]
Thanks so much @mgummelt for releasing this so promptly.

**Pull request merged**
