### PR TITLE
Remove binary index

### PR DESCRIPTION
**Pull request by kensipe**
the binary file is a common source of PR collisions.  It isn't used and this PR removes it.

### CODE REVIEW

**Comment by kensipe** [comment]
@jsancio and @elingg looking for a review.  It is important to note that I have done manual tests verifying that this PR is good and I've removed the binary from the cli-tests branch and ran full tests on the cli which passed.

**Comment by elingg** [comment]
@Kensipe Removing the compressed index file has no effect? In that case, I do think it makes sense to remove for a better user experience. Are any useful checks in the build script getting removed by removing this file?

**Comment by kensipe** [comment]
all checks still exist.. the only script change was the removal of code to build the gz file.

**Comment by elingg** [comment]
LGTM

**Comment by kensipe** [comment]
merging... this has been aggressively tested and had several eyeballs on it.

**Pull request merged**
