### PR TITLE
Add new package for Apache Bookkeeper 4.8.0

### PR DESCRIPTION
**Pull request by eolivelli**

### CODE REVIEW

**Comment by eolivelli** [comment]
cc @jiazhai @sijie

**Comment by jiazhai** [comment]
@eolivelli, From the change, it lgtm.  Not test it yet.

**Comment by jiazhai** [comment]
@jdef, @ryadav88 , Would you please help review or provide some instructions on this PR?
Do we have to make all the checks pass? 
Thanks a lot.

**Comment by eolivelli** [comment]
@jdef, @ryadav88  please take a look

**Comment by vishnu2kmohan** [comment]
Thanks for the contribution @eolivelli, I've kicked off the TeamCity tests.

**Comment by eolivelli** [comment]
Actually we have released Bookkeeper 4.8.1 last week.
Shall I updated the PR.
4.8.0 is now outdated

Thanks

**Comment by vishnu2kmohan** [comment]
Yeah, feel free to bump the Bookkeeper version @eolivelli

**Pull request closed without merging**
