### PR TITLE
Eremetic 0.29 release

### PR DESCRIPTION
**Pull request by ja8zyjits**
I have added a new release for ermetic.

### CODE REVIEW

**Comment by ja8zyjits** [comment]
@realmbgl @ryadav88  please take a look. I have tested this in my local dc/os testing environment. It was working as expected and new version was properly being installed.

**Comment by ja8zyjits** [comment]
@janisz hey can you look into this too?

**Review by janisz — APPROVED** [review]

**Comment by janisz** [comment]
@ja8zyjits Thanks!

**Comment by ja8zyjits** [comment]
@janisz Thanks

**Pull request merged**
