### PR TITLE
remove spark-notebook

### PR DESCRIPTION
**Pull request by mgummelt**
cc @keithchambers PTAL

Remove Spark notebook from universe.

1) We already have a Spark notebook solution in Zeppelin
2) This doesn't install.
  a) The `cd` command attempts to `cd` into a nonexistent directory
  b) `pwd` references the wrong `cwd`, so no java installation is found

I don't believe this ever worked.

### CODE REVIEW

**Comment by andypetrella** [comment]
See https://github.com/mesosphere/universe/pull/397, and you'll have a stable notebook for Spark now ^^
Cc @mhausenblas

**Comment by mhausenblas** [comment]
@mgummelt ad 2) ok, fair enough that needs to be fixed but ad 1) Data Fellas are launch partners submitting a community package; DCOS is an operating system that supports multiple services covering the same problem domain.

@andypetrella can you fix the points 2a and 2b raised above pls?

And yeah, it did work …

**Comment by andypetrella** [comment]
Hey guyz, sure. Actually I think that they are both fixed. 
What we'll work on is a docker image in bridge mode, it's tough with Spark but we have our secret salt that we should integrate sometime in May ^^

**Comment by mhausenblas** [comment]
@mgummelt can you pls verify and merge?

**Comment by mhausenblas** [comment]
@andypetrella has conflicts

**Comment by andypetrella** [comment]
@mhausenblas oh? Which conflicts?

**Comment by mhausenblas** [comment]
@andypetrella see the error message here, merge conflicts. Updates happen here all the time ;)

**Comment by andypetrella** [comment]
@mhausenblas I don't see any error, and the PR has been merged so I don't what you refer here :-)
On this current PR I can't do anything, and I guess it should be just closed and not merged since it goes against https://github.com/mesosphere/universe/pull/397

**Comment by mgummelt** [comment]
Hi guys, sorry, I didn't realize this was being actively maintained.  Looks like we're good to go now.  Since #397 was merged, I'm closing this.

**Comment by andypetrella** [comment]
@mgummelt thanks man! no worries ;-)

**Pull request closed without merging**
