### PR TITLE
Corrects the quobyte-server image name - 2

### PR DESCRIPTION
**Pull request by casusbelli**
Fixes bug #392 in the Quobyte universe package. This is a second PR, old one has been closed

### CODE REVIEW

**Comment by BenWhitehead** [comment]
Please rebase this branch onto `version-2.x` to get the Mesosphere repo validation build to pass

**Comment by casusbelli** [comment]
Rebased and updated, checks have passed.

**Comment by casusbelli** [comment]
@BenWhitehead @kensipe  checks are fine now, i'm standing by if there are any other issues.

**Comment by kensipe** [comment]
@casusbelli could you rebase

**Comment by casusbelli** [comment]
Check's will be done shortly

**Comment by casusbelli** [comment]
Wow, rebase-hell, rebasing again.

**Comment by casusbelli** [comment]
perfect, thanks.

**Pull request merged**
