### PR TITLE
Traefik on DC/OS (DCOS_OSS-1807).

### PR DESCRIPTION
**Pull request by deric**
Traefik is a HTTP reverse proxy and load balancer that supports multiple backends (Marathon, etcd, consul, ZooKeeper, ...). Current version offers simple integration with Marathon backend(s). [Jira Ticket DCOS_OSS-1807](https://jira.mesosphere.com/browse/DCOS_OSS-1807).

### CODE REVIEW

**Comment by joerg84** [comment]
@deric This is great. PR lgtm, but @ryadav88 PTAL

**Comment by bearnard** [comment]
Is there a way to specify something like maxDcosReleaseVersion? Not sure if this will work on 1.1x due to https://github.com/containous/traefik/issues/2115

**Comment by deric** [comment]
@joerg84 Thanks Joerg. 
@bearnard Good point! Currently Traefik Marathon backend `go-marathon` is not fully compatible with Marathon 1.5 API gambol99/go-marathon#324. So, we would have support up to DC/OS 1.9. AFAIK there's no attribute `maxDcosReleaseVersion`. 

There's already a [PR in progress](https://github.com/gambol99/go-marathon/pull/327), hopefully `go-marathon` will be backward compatible with Marathon 1.4, otherwise we would have to require DC/OS >= 1.10. Maybe somebody from Marathon developers could verify the changes?

Meanwhile can we test backwards compatibility with earlier DC/OS releases?

**Comment by ryadav88** [comment]
@deric  please add a documentation example for Traefik. You can create a PR against https://github.com/dcos/examples and use the template from other examples there. 
This is now a requirement for adding new packages to Universe.

**Comment by deric** [comment]
@ryadav88 I've added basic documentation.
@bearnard IMHO missing support for `ipAddresses` feature is not a blocker right now. The upcoming Traefik 1.5.0 (a [rc1](https://github.com/containous/traefik/releases/tag/v1.5.0-rc1) is already available) might fix that. Routing to host ports or containers ports behind NAT works fine.

Traefik web interface is now accessible via DC/OS UI, also I've lowered default CPU and memory requirements. Even `cpu:0.1` and `mem:100` should be enough for testing Traefik.

**Comment by GoelDeepak** [comment]
@deric is there a work in progress to support marathon 1.5?

**Comment by deric** [comment]
@GoelDeepak Yes, see the comments above https://github.com/gambol99/go-marathon/pull/327
I'm testing Traefik against Maraton 1.5.1.2 (DC/OS 1.10.1) so far without problems, but I haven't tested VLANs yet.

**Pull request merged**
