### PR TITLE
Ss/doc link fix

### PR DESCRIPTION
**Pull request by sascala**
did I miss anything that you can see, @joel-hamill ?

### CODE REVIEW

**Comment by joel-hamill** [comment]
LGTM

**Comment by BenWhitehead** [comment]
@joel-hamill @sascala What is the motivation for this change? Packages are supposed to be treated as immutable and not change once published.

**Comment by joel-hamill** [comment]
@BenWhitehead the doc link is wrong. the other change (`DCOS` to `DC/OS` is optional and was bundled in this fix).

**Comment by BenWhitehead** [comment]
@joel-hamill I see. We might need to start tracking the URLs used in packages, since packages will most likely not be able to be updated in the future.

**Comment by joel-hamill** [comment]
@BenWhitehead i totally agree this is unsustainable long term. seems like maybe we should keep this kind of usage info in the actual universe repo.

**Pull request merged**
