### PR TITLE
[WIP] Gerrit package for DC/OS

### PR DESCRIPTION
**Pull request by rji**
This is the initial commit for a Gerrit package for DC/OS. It is meant
to be used with https://github.com/mesosphere/gerrit-dcos. Note that
this hasn't been tested yet.

### CODE REVIEW

**Comment by ssk2** [comment]
@ryadav88, assigning this to you to take it to the finish line (whenever you have time).

**Comment by ryadav88** [comment]
@ssk2 @rji It only needs testing?

**Comment by ssk2** [comment]
@ryadav88: I'm unsure if it was working fully. @rji can comment. I think it's 80% of the way there.

**Comment by joerg84** [comment]
@ssk2 @rji is this still being worked on?

**Pull request closed without merging**
