### PR TITLE
adding marathon-0.15.1

### PR DESCRIPTION
**Pull request by meichstedt**
Adjusted default params:
```
reconciliation_interval: 10 minutes (was 5 minutes)
max_tasks_per_offer: 1 (was 100)
launch_tokens: 100 (was 1000)
```

### CODE REVIEW

**Comment by aquamatthias** [comment]
@meichstedt please rebase

**Comment by aquamatthias** [comment]
Otherwise LGTM.

**Comment by meichstedt** [comment]
rebased!

**Comment by aquamatthias** [comment]
Thanks!

**Pull request merged**
