### PR TITLE
Add cli command to kubernetes

### PR DESCRIPTION
**Pull request by sttts**

### CODE REVIEW

**Comment by kensipe** [comment]
@sttts I just did a quick test.. it appears broken.  

installing k8s CLI subcommands results in:

```
 File "/Users/kensipe/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/basecommand.py", line 223, in main
    status = self.run(options, args)
  File "/Users/kensipe/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/commands/install.py", line 270, in run
    wheel_cache
  File "/Users/kensipe/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/basecommand.py", line 294, in populate_requirement_set
    wheel_cache=wheel_cache):
  File "/Users/kensipe/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/req/req_file.py", line 89, in parse_requirements
    for req in req_iter:
  File "/Users/kensipe/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/req/req_file.py", line 137, in process_line
    isolated=isolated, options=req_options, wheel_cache=wheel_cache
  File "/Users/kensipe/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/req/req_install.py", line 212, in from_line
    wheel_cache=wheel_cache, constraint=constraint)
  File "/Users/kensipe/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/req/req_install.py", line 66, in __init__
    req = pkg_resources.Requirement.parse(req)
  File "/Users/kensipe/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2980, in parse
    reqs = list(parse_requirements(s))
  File "/Users/kensipe/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2924, in parse_requirements
    "version spec")
  File "/Users/kensipe/.dcos/subcommands/kubernetes/env/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2889, in scan_list
    raise RequirementParseError(msg, line, "at", line[p:])
RequirementParseError: Expected version spec in git@github.com:mesosphere/dcos-kubernetes-cli.git#egg=dcos-kubernetes at @github.com:mesosphere/dcos-kubernetes-cli.git#egg=dcos-kubernetes
```

**Comment by sttts** [comment]
Yes. We are working on new dcos packages for k8s now. Next step would be to update this.

**Comment by elingg** [comment]
After discussion with @karlkfi and @jdef, it seems this PR is blocked by https://github.com/mesosphere/kubernetes-mesos/pull/421, but this should get in soon.

**Comment by kensipe** [comment]
@elingg @karlkfi @jdef 421 is merged... and kubernetes is moved to the multiverse.  please send a PR there.

**Comment by kensipe** [comment]
@sttts and @jdef can I close this PR?

**Comment by sttts** [comment]
Closing. Follow-up PR will be opened against multiverse.

**Pull request closed without merging**
