### PR TITLE
add swarm command

### PR DESCRIPTION
**Pull request by vieux**
Signed-off-by: Victor Vieux <victorvieux@gmail.com>

### CODE REVIEW

**Comment by vieux** [comment]
@tnachen the CI says the test fails but I cannot see why because it's on teamcity >.<

**Comment by kensipe** [comment]
@vieux I'll take a look... is this ready for review (assume the build succeeds)?

**Comment by kensipe** [comment]
the issue is here: 

```
[14:14:42][Step 1/1] diff --git a/repo/meta/index.json.gz b/repo/meta/index.json.gz
[14:14:42][Step 1/1] index 2d33b0b..67e115e 100644
[14:14:42][Step 1/1] Binary files a/repo/meta/index.json.gz and b/repo/meta/index.json.gz differ
[14:14:42][Step 1/1] Process exited with code 1
[14:14:42][Step 1/1] Step Command Line failed
```

**Comment by vieux** [comment]
should be good now

**Comment by tnachen** [comment]
Merging for now as our CI is down and it looks good to me

**Pull request merged**
