### PR TITLE
Add redis cluster

### PR DESCRIPTION
**Pull request by harryge00**
Currently, our community only has a single redis catalog service. I added a redis-cluster: https://redis.io/topics/cluster-tutorial

TODO:
1. Move `hge-dcos.s3.amazonaws.com/autodelete7d/redis-cluster/` to a official S3 address.
2. Here official redis image is used. But I think we can push to mesosphere's docker repo if necessary.

### CODE REVIEW

**Comment by kaiwalyajoshi** [comment]
@harryge00 there was a tooling issue due to Docker CLI breaking upstream which has been [worked-around](https://github.com/mesosphere/universe-package-builder/pull/22).

The previous breaking CI has been restarted and has succeded, feel free to merged when ready.

**Review by kaiwalyajoshi — APPROVED** [review]

**Review by kaiwalyajoshi — CHANGES_REQUESTED** [review]
@harryge00 thanks for the patch, we should move this into a seperate `redis-cluster` folder and make the stubs found here permanent.

**Comment by harryge00** [comment]
@kaiwalyajoshi  Is this repo https://github.com/mesosphere/universe-package-builder/ private? I shall ask for permission first.

**Comment by kaiwalyajoshi** [comment]
@harryge00 universe-package-builder is mostly for Mesosphere internal build CI tooling and hence is private. Is there something specific you need from that repository?

**Comment by harryge00** [comment]
@kaiwalyajoshi Thanks for your review. I have downloaded `universe-package-builder` and use the script to trigger building:
```
export S3_BUCKET_URL=s3://hge-dcos/autodelete7d
echo "redis-cluster" >> WHITELIST # It throws "redis-cluster is not whitelisted" if not add it to WHITELIST
cd scripts
./build-universe.sh $UNIVERSE $OUTDIR
```
The final part of log is :
```
 return 0
+ [[ 0 -eq 1 ]]
+ '[' -z '' ']'
+ next=1
++ get_package_alphabet redis-cluster
++ local name=redis-cluster
++ tr /a-z/ /A-Z/
+ LETTER=R
+ '[' -d /home/ec2-user/coding/universe/repo/packages/R/redis-cluster/1/ ']'
+ uploadToS3 redis-cluster 0.1.0-5.0.5
+ : s3://hge-dcos/autodelete7d
+ : 86aada14
+ cd /home/ec2-user/dcos/universe
+ build_def=redis-cluster-0.1.0-5.0.5.json
+ file_name=redis-cluster-0.1.0-5.0.5.dcos
++ sha1sum redis-cluster-0.1.0-5.0.5.dcos
++ awk '{print $1}'
+ sha1_value=ffade79bc105a74b45efa345a31a5dfbf5dd2b9a
+ sha1_file=redis-cluster-0.1.0-5.0.5.dcos.sha1
+ echo 'ffade79bc105a74b45efa345a31a5dfbf5dd2b9a redis-cluster-0.1.0-5.0.5.dcos'
+ aws s3 cp --acl bucket-owner-full-control --quiet redis-cluster-0.1.0-5.0.5.json s3://hge-dcos/autodelete7d/redis-cluster/0.1.0-5.0.5/redis-cluster-0.1.0-5.0.5.json
+ aws s3 cp --acl bucket-owner-full-control --quiet redis-cluster-0.1.0-5.0.5.dcos s3://hge-dcos/autodelete7d/redis-cluster/0.1.0-5.0.5/redis-cluster-0.1.0-5.0.5.dcos
+ aws s3 cp --acl bucket-owner-full-control --quiet redis-cluster-0.1.0-5.0.5.dcos s3://hge-dcos/autodelete7d/redis-cluster/0.1.0-5.0.5/86aada14-ffade79/redis-cluster-0.1.0-5.0.5.dcos
+ aws s3 cp --acl bucket-owner-full-control --quiet redis-cluster-0.1.0-5.0.5.dcos.sha1 s3://hge-dcos/autodelete7d/redis-cluster/0.1.0-5.0.5/redis-cluster-0.1.0-5.0.5.dcos.sha1
+ aws s3 cp --acl bucket-owner-full-control --quiet redis-cluster-0.1.0-5.0.5.dcos.sha1 s3://hge-dcos/autodelete7d/redis-cluster/0.1.0-5.0.5/86aada14-ffade79/redis-cluster-0.1.0-5.0.5.dcos.sha1
+ cd /home/ec2-user/coding/universe-package-builder/scripts
```
As you can see, the script upload `dcos` and `json` to `S3`. I am not sure if this will this would solve the tooling issue.

**Review by kaiwalyajoshi — APPROVED** [review]

**Pull request merged**
