### PR TITLE
Initial commit for PX Univ update

### PR DESCRIPTION
**Pull request by jsilberm**
Updating the Portworx Universe Catalog to more easily support upcoming features.

### CODE REVIEW

**Comment by jsilberm** [comment]
Corresponding Docs PR submitted:  https://github.com/dcos/examples/pull/61

Good to go on my side.  Please complete the merge or let me know what needs to be fixed.   Thanks.

**Comment by jsilberm** [comment]
Ping?

**Comment by ryadav88** [comment]
@jsilberm will review it today.

**Comment by ryadav88** [comment]
LGTM! 👍

**Pull request merged**
