### PR TITLE
Upgrade CP to 3.3.1

### PR DESCRIPTION
**Pull request by maxzheng**
```
confluent-connect
--------------------------------------------------------------------------------
Only in repo/packages/C/confluent-connect/9: .package.json.swp
diff repo/packages/C/confluent-connect/8/package.json repo/packages/C/confluent-connect/9/package.json
4c4
<   "version": "1.0.0-3.3.0",
---
>   "version": "1.0.0-3.3.1",
6c6
<   "description": "Confluent Connect worker\n\n\tDocumentation: http://docs.confluent.io/3.3.0/connect/managing.html",
---
>   "description": "Confluent Connect worker\n\n\tDocumentation: http://docs.confluent.io/3.3.1/connect/managing.html",
diff repo/packages/C/confluent-connect/8/resource.json repo/packages/C/confluent-connect/9/resource.json
5c5
<         "image": "confluentinc/cp-kafka-connect:3.3.0"
---
>         "image": "confluentinc/cp-kafka-connect:3.3.1"

confluent-control-center
--------------------------------------------------------------------------------
diff repo/packages/C/confluent-control-center/9/package.json repo/packages/C/confluent-control-center/10/package.json
4c4
<   "version": "1.0.0-3.3.0",
---
>   "version": "1.0.0-3.3.1",
6c6
<   "description": "Confluent Control Center service\n\n\tDocumentation: http://docs.confluent.io/3.3.0/control-center/docs/userguide.html\n\tDC/OS Specifics: https://www.confluent.io/whitepaper/deploying-confluent-platform-with-mesosphere",
---
>   "description": "Confluent Control Center service\n\n\tDocumentation: http://docs.confluent.io/3.3.1/control-center/docs/userguide.html\n\tDC/OS Specifics: https://www.confluent.io/whitepaper/deploying-confluent-platform-with-mesosphere",
diff repo/packages/C/confluent-control-center/9/resource.json repo/packages/C/confluent-control-center/10/resource.json
5c5
<         "image": "confluentinc/cp-enterprise-control-center:3.3.0"
---
>         "image": "confluentinc/cp-enterprise-control-center:3.3.1"

confluent-replicator
--------------------------------------------------------------------------------
diff repo/packages/C/confluent-replicator/5/package.json repo/packages/C/confluent-replicator/6/package.json
4c4
<   "version": "1.0.0-3.3.0",
---
>   "version": "1.0.0-3.3.1",
6c6
<   "description": "Confluent Enterprise Replicator for multi-data center synchronization of topic data\n\n\tDocumentation: http://docs.confluent.io/3.3.0/connect/connect-replicator/docs/index.html",
---
>   "description": "Confluent Enterprise Replicator for multi-data center synchronization of topic data\n\n\tDocumentation: http://docs.confluent.io/3.3.1/connect/connect-replicator/docs/index.html",
diff repo/packages/C/confluent-replicator/5/resource.json repo/packages/C/confluent-replicator/6/resource.json
5c5
<         "image": "confluentinc/cp-enterprise-replicator:3.3.0"
---
>         "image": "confluentinc/cp-enterprise-replicator:3.3.1"

confluent-rest-proxy
--------------------------------------------------------------------------------
diff repo/packages/C/confluent-rest-proxy/8/config.json repo/packages/C/confluent-rest-proxy/9/config.json
53c53,62
< 
---
>           "type": "string"
>         },
>         "access-control-allow-methods": {
>           "default": "",
>           "description": "Set value to Jetty Access-Control-Allow-Origin header for specified methods",
>           "type": "string"
>         },
>         "access-control-allow-origin": {
>           "default": "",
>           "description": "Set value for Jetty Access-Control-Allow-Origin header",
diff repo/packages/C/confluent-rest-proxy/8/marathon.json.mustache repo/packages/C/confluent-rest-proxy/9/marathon.json.mustache
35c35,37
<     "KAFKA_REST_SCHEMA_REGISTRY_URL": "http://{{proxy.schema-registry-service}}.marathon.l4lb.thisdcos.directory:8081"
---
>     "KAFKA_REST_SCHEMA_REGISTRY_URL": "http://{{proxy.schema-registry-service}}.marathon.l4lb.thisdcos.directory:8081",
>     "KAFKA_REST_ACCESS_CONTROL_ALLOW_METHODS": "{{proxy.access-control-allow-methods}}",
>     "KAFKA_REST_ACCESS_CONTROL_ALLOW_ORIGIN": "{{proxy.access-control-allow-origin}}"
diff repo/packages/C/confluent-rest-proxy/8/package.json repo/packages/C/confluent-rest-proxy/9/package.json
4c4
<   "version": "1.0.0-3.3.0",
---
>   "version": "1.0.0-3.3.1",
6c6
<   "description": "Confluent REST Proxy service\n\n\tDocumentation: http://docs.confluent.io/3.3.0/kafka-rest/docs/api.html",
---
>   "description": "Confluent REST Proxy service\n\n\tDocumentation: http://docs.confluent.io/3.3.1/kafka-rest/docs/api.html",
diff repo/packages/C/confluent-rest-proxy/8/resource.json repo/packages/C/confluent-rest-proxy/9/resource.json
5c5
<         "image": "confluentinc/cp-kafka-rest:3.3.0"
---
>         "image": "confluentinc/cp-kafka-rest:3.3.1"

confluent-schema-registry
--------------------------------------------------------------------------------
diff repo/packages/C/confluent-schema-registry/9/config.json repo/packages/C/confluent-schema-registry/10/config.json
49a50,59
>         },
>         "access-control-allow-methods": {
>           "default": "",
>           "description": "Set value to Jetty Access-Control-Allow-Origin header for specified methods",
>           "type": "string"
>         },
>         "access-control-allow-origin": {
>           "default": "",
>           "description": "Set value for Jetty Access-Control-Allow-Origin header",
>           "type": "string"
diff repo/packages/C/confluent-schema-registry/9/marathon.json.mustache repo/packages/C/confluent-schema-registry/10/marathon.json.mustache
34c34,36
<     "SCHEMA_REGISTRY_SCHEMA_REGISTRY_ZK_NAMESPACE": "{{registry.kafkastore}}/{{registry.name}}"
---
>     "SCHEMA_REGISTRY_SCHEMA_REGISTRY_ZK_NAMESPACE": "{{registry.kafkastore}}/{{registry.name}}",
>     "SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_METHODS": "{{registry.access-control-allow-methods}}",
>     "SCHEMA_REGISTRY_ACCESS_CONTROL_ALLOW_ORIGIN": "{{registry.access-control-allow-origin}}"
diff repo/packages/C/confluent-schema-registry/9/package.json repo/packages/C/confluent-schema-registry/10/package.json
4c4
<   "version": "1.0.0-3.3.0",
---
>   "version": "1.0.0-3.3.1",
6c6
<   "description": "Confluent Schema Registry service\n\n\tDocumentation: http://docs.confluent.io/3.3.0/schema-registry/docs/intro.html",
---
>   "description": "Confluent Schema Registry service\n\n\tDocumentation: http://docs.confluent.io/3.3.1/schema-registry/docs/intro.html",
diff repo/packages/C/confluent-schema-registry/9/resource.json repo/packages/C/confluent-schema-registry/10/resource.json
5c5
<         "image": "confluentinc/cp-schema-registry:3.3.0"
---
>         "image": "confluentinc/cp-schema-registry:3.3.1"

```

### CODE REVIEW

**Comment by triclambert** [comment]
@benclarkwood should we upgrade the scheduler at the same time?

**Comment by benclarkwood** [comment]
@triclambert do you mean, "should we update the confluent-kafka package at the same time"?

**Comment by maxzheng** [comment]
@benclarkwood ok to checkin?

**Comment by triclambert** [comment]
@benclarkwood this PR only changes the CP package, it does not update the scheduler.  I'm just wondering if there was a change there we should also pull in with this release.

**Comment by benclarkwood** [comment]
@triclambert Yes, my plan was to wait until we release the Confluent-Kafka package.

**Comment by maxzheng** [comment]
@benclarkwood can u confirm that you are working on releasing cp kafka package? My PR for that was merged. Let me know if there is anything else that I need to do from my side. Thx!

**Comment by benclarkwood** [comment]
@maxzheng Yes, that release will move forward ~ next week.

**Comment by maxzheng** [comment]
@benclarkwood Are we on track for this & kafka scheduler to go out this week? If so, which day? Thx

**Pull request merged**
