### PR TITLE
add nginx package based on bitnami/nginx:1.10.1-r1

### PR DESCRIPTION
**Pull request by sameersbn**
We would like to take over the maintenance of the Nginx package, using the [Bitnami Docker Image for NGINX](https://github.com/bitnami/bitnami-docker-nginx).

This update is backward compatible with the current NGINX package.

[Why Bitnami?](https://bitnami.com/learn_more#benefits)

### CODE REVIEW

**Comment by ssk2** [comment]
Hey @sameersbn: this looks great! Thank you!

I was wondering if you could incorporate the changes I made in https://github.com/mesosphere/universe/pull/642? I'll give this a test when that's done and we should be good to merge.

**Comment by sameersbn** [comment]
Thanks @ssk2. I'll update the PR with th changes from the reference PR. Thanks again.

**Comment by ssk2** [comment]
Could you please also add the following line to your package.json? https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/A/artifactory-lb/0/package.json#L9

**Comment by sameersbn** [comment]
@ssk2 updated with the suggested changes.

**Comment by ssk2** [comment]
Looks good!

**Pull request merged**
