### PR TITLE
update Datadog package to 5.18.1

### PR DESCRIPTION
**Pull request by xvello**
This PR updates the Datadog package to the latest 5.18.1:

- update image hash to use 12.4.5181
- remove supervisord port mapping
- update healthcheck to use /probe.sh command

Full diff from previous package version 3

```
diff -u 3/config.json 4/config.json
--- 3/config.json	2017-09-19 10:18:04.000000000 +0200
+++ 4/config.json	2017-09-19 11:25:31.000000000 +0200
@@ -34,11 +34,6 @@
                     "default": 8125,
                     "description": "statsD port",
                     "type": "integer"
-                },
-                "supervisor_port": {
-                    "default": 9001,
-                    "description": "Agent supervisord port",
-                    "type": "integer"
                 }
             },
             "required": [
diff -u 3/marathon.json.mustache 4/marathon.json.mustache
--- 3/marathon.json.mustache	2017-10-19 10:40:48.000000000 +0200
+++ 4/marathon.json.mustache	2017-10-19 10:42:43.000000000 +0200
@@ -3,7 +3,7 @@
     "container": {
         "type": "DOCKER",
         "docker": {
-            "image": "{{resource.assets.container.docker.73925bb9ab66}}",
+            "image": "{{resource.assets.container.docker.a5669b334fa2}}",
             "parameters": [
                 {
                     "key": "name", "value": "dd-agent"
@@ -15,13 +15,12 @@
                     "key": "env", "value": "MESOS_SLAVE=true"
                 },
                 {
-                    "key": "env", "value": "SD_BACKEND=docker"                
+                    "key": "env", "value": "SD_BACKEND=docker"
                 }
             ],
             "network": "BRIDGE",
             "portMappings": [
-                { "hostPort": {{datadog.statsd_port}}, "containerPort": 8125, "protocol": "udp" },
-                { "hostPort": {{datadog.supervisor_port}}, "containerPort": 9001, "protocol": "tcp" }
+                { "hostPort": {{datadog.statsd_port}}, "containerPort": 8125, "protocol": "udp" }
             ]
         },
         "volumes": [
@@ -52,14 +51,12 @@
     ],
     "healthChecks": [
         {
-            "path": "/",
-            "portIndex": 1,
-            "protocol": "HTTP",
+            "protocol": "COMMAND",
+            "command": { "value": "/probe.sh" },
             "gracePeriodSeconds": 300,
             "intervalSeconds": 60,
             "timeoutSeconds": 20,
-            "maxConsecutiveFailures": 3,
-            "ignoreHttp1xx": false
+            "maxConsecutiveFailures": 3
         }
     ]
 }
diff -u 3/package.json 4/package.json
--- 3/package.json	2017-09-19 10:18:04.000000000 +0200
+++ 4/package.json	2017-10-18 11:36:05.000000000 +0200
@@ -19,6 +19,6 @@
         "datadog",
         "monitoring"
     ],
-    "version": "5.16.0",
+    "version": "5.18.1",
     "website": "https://www.datadoghq.com/"
 }
diff -u 3/resource.json 4/resource.json
--- 3/resource.json	2017-10-19 10:40:48.000000000 +0200
+++ 4/resource.json	2017-10-18 11:36:02.000000000 +0200
@@ -2,7 +2,7 @@
   "assets": {
     "container": {
       "docker": {
-        "73925bb9ab66": "datadog/docker-dd-agent:11.0.5160"
+        "a5669b334fa2": "datadog/docker-dd-agent:12.4.5181"
       }
     }
   },
```

### CODE REVIEW

**Comment by irabinovitch** [comment]
@ryadav88 Could we get a hand in getting this merged today?

**Comment by ryadav88** [comment]
@xvello can you please verify that this works on dc/os 1.10. 
Stderr : 
```I0919 22:06:20.100862  3341 exec.cpp:162] Version: 1.4.0
I0919 22:06:20.104564  3354 exec.cpp:237] Executor registered on agent 4b082fb4-4993-4ab7-94d9-c36dfeadddb4-S2
I0919 22:06:20.105561  3350 executor.cpp:120] Registered docker executor on 10.0.2.251
I0919 22:06:20.106025  3353 executor.cpp:160] Starting task datadog-agent.b68cab79-9d86-11e7-8dac-9eb7a327d997
I0919 22:10:59.290809  3355 executor.cpp:269] Received killTask for task datadog-agent.b68cab79-9d86-11e7-8dac-9eb7a327d997
I0919 22:11:04.246886  3353 executor.cpp:269] Received killTask for task datadog-agent.b68cab79-9d86-11e7-8dac-9eb7a327d997
I0919 22:11:09.247002  3356 executor.cpp:269] Received killTask for task datadog-agent.b68cab79-9d86-11e7-8dac-9eb7a327d997```

**Comment by irabinovitch** [comment]
@ryadav88 Did you have a chance to review @hkaj 's updates?

**Comment by ryadav88** [comment]
@xvello I get a invalid json error when deploying the package. Did you test it with DC/OS 1.10? 
Also, please update the documentation here to add example for 1.10 https://github.com/dcos/examples/tree/master/datadog/

**Comment by irabinovitch** [comment]
@ryadav88 We have not yet tested against 1.10 yet, but will do so as soon as we have a 1.10 cluster online.  In the mean time, please help us get this merged so that 1.9.x and 1.8.x users can get this security update deployed ASAP.

**Comment by xvello** [comment]
@ryadav88 looks like the issue is the healthcheck command. Is it required, or can marathon pick up the docker healthcheck baked in the image?

**Comment by irabinovitch** [comment]
@ryadav88 ping?

**Comment by ryadav88** [comment]
@irabinovitch moving out email conversation here. 

@xvello 
- I tested the PR with 1.9 before your latest change. Have you verified the installation against 1.9? 
- the reason I ask that the PR be tested against 1.10 is that the visibility of packages is controlled by the minDcosReleaseVersion property. In this case, the Datadog package will be visible on all dc/os clusters starting 1.8 and will not even work in 1.10 clusters. 
- If you are not able to test against 1.10, then please add this caveat at the beginning of `preInstallNotes` in package.json : 
"Datadog package doesn't work on 1.10 clusters. This is a known issue and will be fixed by the Datadog team in the next revision."

**Comment by xvello** [comment]
Hello,

I now installs and deploys on 1.9.4 and 1.10.0, using `mesosphere/universe-server:20171019T084324Z-pull-1430-8f5463a3cc` as a local registry, and metrics come though: 

hostmap

The issue I have now is the service shows as healthy on 1.9.4

healthy on 1.9

but gets stuck in `staging` on 1.10.0 although the agent runs OK and manually running the healthcheck runs OK:

staging on 1.10.0

healthcheck ok on 1.10.0

Here's the output of `dcos marathon app show /datadog-agent` on both clusters : https://gist.github.com/xvello/d22869385b24e83c422e52ebc037dba5

do you have any idea what could cause this issue?

**Comment by xvello** [comment]
@ryadav88 @irabinovitch As we need to ship this security update ASAP, I added the `preInstallNotes` line about 1.10 compatibility, and will open an issue to diagnose the 1.10 compatibility.

Can we merge with this note?

**Comment by ryadav88** [comment]
@xvello thanks for adding the note. LGTM. I've also reached out to our team to understand why you are seeing this issue.

**Pull request merged**
