### PR TITLE
Added Jenkins version to service package version

### PR DESCRIPTION
**Pull request by tommysdk**
Added the Jenkins version to the service package version since there are many different Jenkins versions available with different characteristics (JDK support, plugin compatibility etc) and it would be useful to know which Jenkins version to install when selecting a Jenkins package in DC/OS. With current master, there is no obvious way to know the Jenkins version beforehand.

This also aligns with other packages that uses the same denotation.

### CODE REVIEW

**Comment by mhausenblas** [comment]
@ssk2 can you pls review this PR? Has been sitting here for almost a month :(

**Comment by ssk2** [comment]
Oops, apologies @tommysdk. I can't merge this into the current package because we're about to significantly refactor this package (next week) but I will make sure this change happens.

**Comment by tommysdk** [comment]
@ssk2 ok. Would appreciate a notification when the change has been introduced!

**Comment by ssk2** [comment]
@tommysdk, we are now doing this: https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/J/jenkins/11/package.json#L4

**Comment by tommysdk** [comment]
@ssk2 nice, thanks!

**Pull request closed without merging**
