### PR TITLE
[wip] Artifactory package updates

### PR DESCRIPTION
**Pull request by ssk2**
To Do:
- [x] Make license necessary
- [x] Update version
- [x] Remove support for local persistent volumes
- [ ] Update screenshots in documentation
- [ ] Update documentation to use new config
- [ ] Submit pull request to [dcos/examples](https://github.com/dcos/examples)
- [ ] Update docs to reference using a hostname

### CODE REVIEW

**Comment by ryadav88** [comment]
@ssk2 are you still working on this PR?

**Comment by ssk2** [comment]
I'll resurrect it on Friday!

**Comment by ryadav88** [comment]
@ssk2 @jainishshah17 is this ready for review?

**Comment by ssk2** [comment]
@ryadav88: need to re-test that some fixes went in. Will do so this morning.

**Comment by jainishshah17** [comment]
@ssk2  : any updates?

**Comment by jainishshah17** [comment]
https://github.com/dcos/examples/pull/52

**Comment by jainishshah17** [comment]
@ryadav88 @ssk2 ping

**Comment by joerg84** [comment]
As discussed with @ryadav88  I will merge this despite the pending review for examples.

**Comment by fernandosanchezmunoz** [comment]
thanks @ssk2 @joerg84 !

**Pull request merged**
