### PR TITLE
OGC Preview web application

### PR DESCRIPTION
**Pull request by gisjedi**
Discover, browse and export data from OGC service layers exposed by way of WMS/WFS service interfaces, with a special focus given to time-enabled data. Defaults to using an existing install of the GeoServer package in a previous pull request. Install settings can be provided to point app at an externally hosted GeoServer, as well.

Resubmission to satisfy requested 3.0 packaging update from #476.

### CODE REVIEW

**Comment by ryadav88** [comment]
@gisjedi I see that this PR has been here for some time now. Please update it and let me know if its ready to be reviewed.

**Comment by ryadav88** [comment]
@gisjedi any update here?

**Comment by ryadav88** [comment]
@gisjedi please lmk if this PR should be closed?

**Comment by gisjedi** [comment]
@ryadav88 I was planning to push this today, but there were some downstream updates that haven't made it back. I'm going to try to get that addressed tomorrow and then we should be able to close this out.

**Comment by gisjedi** [comment]
I've got these changes in from downstream, but it'll take me a business day or two to finish testing. Hopefully early next week to finalize.

**Comment by gisjedi** [comment]
This is still on my todo list, but I've gotten derailed with some other tasking. I get most of next week free, so I'm going to try to coordinate with others to finish the fixes and get this release in. Thanks for leaving this open. Happy holidays!

**Comment by ryadav88** [comment]
that sounds good. thanks for the update.

**Comment by ryadav88** [comment]
@gisjedi any updates here?

**Comment by gisjedi** [comment]
@ryadav88 So I've gotta pulled off on other priorities for the time being and am still waiting on some other guys to get back with me as to downstream updates. Lets close for now so it doesn't just languish and I'll reopen when its ready. Thanks for you patience.

**Comment by ryadav88** [comment]
thanks for the update. Will reopen when the upstream changes are ready. let me know.

**Pull request closed without merging**
