### PR TITLE
ArangoDB 0.4.0 supporting OAuth, binary installation

### PR DESCRIPTION
**Pull request by m0ppers**
retargeting 3.x

see #479

### CODE REVIEW

**Comment by BenWhitehead** [comment]
Merge blocked by #480

**Comment by BenWhitehead** [comment]
@m0ppers Can you please rebase this (not merge, a few commits had to be rewritten when switching over to version-3.x)? things should be good to go after a rebase.

**Comment by m0ppers** [comment]
rebased..is there a time frame when this will be merged?

**Comment by BenWhitehead** [comment]
@tamarrow Can you provide some guidance to @m0ppers on how to get a windows cli built? Having a windows cli defined is the last thing preventing this PR from having green builds across the board.

**Comment by m0ppers** [comment]
don't merge yet...apparently this change here https://github.com/dcos/dcos-cli/commit/2185eb32ee0960059306ce2ff98ff5426924ce8c affects us...locally (linux) I had an older dcos module version and that worked fine. for the other platforms I didn't have a cluster to test against and so I was happy as soon as the binary showed the help...have to recheck all platforms again...

**Comment by tamarrow** [comment]
@m0ppers you should pin the `dcos` module to a particular version.

**Comment by m0ppers** [comment]
done

**Comment by tamarrow** [comment]
@m0ppers you have files in this commit for `enterprise-security-cli`, probably from a merge. Can you remove them and I'll merge the pr? Thanks!

**Pull request merged**
