### PR TITLE
Added command-line option to use external ETCD cluster

### PR DESCRIPTION
**Pull request by fceller**

### CODE REVIEW

**Comment by BenWhitehead** [comment]
please retarget this PR at branch `version-2.x`

**Comment by kensipe** [comment]
@fceller did you get this moved to version-2.x?  looking to close this PR

**Comment by fceller** [comment]
this pull request is about the backport to 1.x. in case 1.x is obsolete this pull request would be obsolete too. in case 1.x is still relevant please merge

**Comment by pyronicide** [comment]
@fceller 1.x is mostly obsolete.

**Pull request closed without merging**
