### PR TITLE
gestalt-framework 1.0.0 launcher release

### PR DESCRIPTION
**Pull request by cgbaker**
added eula to licenses and requirement in config
removed mesos config from gestalt launcher
added lambda.scale-down-timeout config for gestalt-framework launcher
updated docker images
added config for laser min/max port range, injected into launcher payload
added database.num-secondaries config
removed defunct config for framework launcher

### CODE REVIEW

**Comment by cgbaker** [comment]
@pyronicide , anything else that i need to do here?

**Comment by joerg84** [comment]
@cgbaker looks good to me, did you test install it?

**Comment by cgbaker** [comment]
Many, many times :)

I've been running it from https://universe.galacticfog.com for a few weeks
for internal and customer use.

**Comment by joerg84** [comment]
LGTM

**Pull request merged**
