### PR TITLE
Update Jenkins to 0.2.0

### PR DESCRIPTION
**Pull request by ssk2**
Merge after https://github.com/mesosphere/jenkins-mesos/pull/33.

### CODE REVIEW

**Comment by rji** [comment]
:+1: once https://github.com/mesosphere/jenkins-mesos/pull/33 is merged and CI finishes.

**Comment by rji** [comment]
Actually, if we like the approach in https://github.com/mesosphere/jenkins-mesos/pull/32, we should get that PR merged too before releasing 0.2.0.

**Comment by rji** [comment]
This should be ready to merge once https://github.com/mesosphere/jenkins-mesos/pull/36 is merged and 0.2.0 is tagged and shipped.

**Comment by ssk2** [comment]
:+1:

**Comment by ssk2** [comment]
Currently tagging that release now, once we've pushed the new image, I'd like to test this once more manually before merging.

**Comment by ssk2** [comment]
Hey @rji - you need to add the environment variable to:
```  "env": {
      "JENKINS_FRAMEWORK_NAME": "{{jenkins.framework-name}}",
      "JENKINS_CONTEXT": "/service/{{jenkins.framework-name}}",
      "JENKINS_MESOS_MASTER": "{{jenkins.mesos-master}}",
      "JVM_OPTS": "{{jenkins.jvm-opts}}",
      "LD_LIBRARY_PATH": "/opt/mesosphere/lib"
  },
```

**Comment by rji** [comment]
Right, one sec!

**Comment by rji** [comment]
Hey @ssk2, check this out and let me know how your testing goes. Fwiw, I squashed the two commits to one as well.

**Pull request merged**
