### PR TITLE
Add new arangodb release

### PR DESCRIPTION
**Pull request by m0ppers**

### CODE REVIEW

**Comment by joerg84** [comment]
Just tested and had some issues which I am currently discussing with Max. Will update this note after the discussion.

**Comment by joerg84** [comment]
After the above fixes (+ CLI fixes) I tested this on the continuous build and Stable including running some queries. LGTM @kensipe could you have a second look and then either you or myself can merge this.

**Comment by kensipe** [comment]
looking!

**Comment by kensipe** [comment]
installs and crashes with 1-2 mins... fails to run on a stable version of dcos.

**Comment by neunhoef** [comment]
We tried with the dcos you get with the current AWS cloud formation template. Is this the stable version of dcos you are referring to? Can you please give us some more info about the type of crash or any log messages? Maybe on the dcos-community slack? Please send to @neunhoef and to @mop there.

**Comment by joerg84** [comment]
@kensipe Could it be you didn't add the `arangodb` role to the master flags and restarted the master? Works fine for me. See https://github.com/arangodb/arangodb-dcos#installationstartup for details.

**Comment by joerg84** [comment]
As discussed with with Ken and Jose we added a warning to the preInstallNotes that -due to the fact that it uses persistent volumes- only works with >= DCOS 1.3.

**Pull request merged**
