### PR TITLE
Release Jenkins 3.5.4-2.150.1 with strict mode support

### PR DESCRIPTION
**Pull request by kvish**
```
diff 29/marathon.json.mustache 30/marathon.json.mustache
7,15d6
<   "container": {
<       "type": "MESOS",
<       "volumes":[
<         {
<             "containerPath": "secrets/service-account.json",
<             "secret": "serviceCredential"
<         }
<       ]
<   },
29c20
<           "DCOS_SERVICE_ACCOUNT_CREDENTIAL": "secrets/service-account.json",
---
>           "DCOS_SERVICE_ACCOUNT_CREDENTIAL": { "secret": "serviceCredential" },
53c44
<            "image": "{{resource.assets.container.docker.jenkins-353-21501}}",
---
>            "image": "{{resource.assets.container.docker.jenkins-354-21501}}",
diff 29/package.json 30/package.json
4c4
<   "version": "3.5.3-2.150.1",
---
>   "version": "3.5.4-2.150.1",
diff 29/resource.json 30/resource.json
10c10
<         "jenkins-353-21501": "mesosphere/jenkins:3.5.3-2.150.1"
---
>         "jenkins-354-21501": "mesosphere/jenkins:3.5.4-2.150.1"
```

### CODE REVIEW

**Review by takirala — APPROVED** [review]

**Comment by kvish** [comment]
<   "container": {
<       "type": "MESOS",
<       "volumes":[
<         {
<             "containerPath": "secrets/service-account.json",
<             "secret": "serviceCredential"
<         }
<       ]
<   },
29c20
<           "DCOS_SERVICE_ACCOUNT_CREDENTIAL": "secrets/service-account.json",
---
>           "DCOS_SERVICE_ACCOUNT_CREDENTIAL": { "secret": "serviceCredential" },
53c44
<            "image": "{{resource.assets.container.docker.jenkins-353-21501}}",
---
>            "image": "{{resource.assets.container.docker.jenkins-354-21501}}",
diff 29/package.json 30/package.json
4c4
<   "version": "3.5.3-2.150.1",
---
>   "version": "3.5.4-2.150.1",
diff 29/resource.json 30/resource.json
10c10
<         "jenkins-353-21501": "mesosphere/jenkins:3.5.3-2.150.1"
---
>         "jenkins-354-21501": "mesosphere/jenkins:3.5.4-2.150.1"

**Comment by takirala** [comment]
@kvish can we close https://github.com/mesosphere/universe/pull/2213 ?

**Comment by kvish** [comment]
`<   "container": {
<       "type": "MESOS",
<       "volumes":[
<         {
<             "containerPath": "secrets/service-account.json",
<             "secret": "serviceCredential"
<         }
<       ]
<   },
29c20
<           "DCOS_SERVICE_ACCOUNT_CREDENTIAL": "secrets/service-account.json",
---
>           "DCOS_SERVICE_ACCOUNT_CREDENTIAL": { "secret": "serviceCredential" },
53c44
<            "image": "{{resource.assets.container.docker.jenkins-353-21501}}",
---
>            "image": "{{resource.assets.container.docker.jenkins-354-21501}}",
diff 29/package.json 30/package.json
4c4
<   "version": "3.5.3-2.150.1",
---
>   "version": "3.5.4-2.150.1",
diff 29/resource.json 30/resource.json
10c10
<         "jenkins-353-21501": "mesosphere/jenkins:3.5.3-2.150.1"
---
>         "jenkins-354-21501": "mesosphere/jenkins:3.5.4-2.150.1"`

**Comment by kvish** [comment]
```
diff 29/marathon.json.mustache 30/marathon.json.mustache
7,15d6
<   "container": {
<       "type": "MESOS",
<       "volumes":[
<         {
<             "containerPath": "secrets/service-account.json",
<             "secret": "serviceCredential"
<         }
<       ]
<   },
29c20
<           "DCOS_SERVICE_ACCOUNT_CREDENTIAL": "secrets/service-account.json",
---
>           "DCOS_SERVICE_ACCOUNT_CREDENTIAL": { "secret": "serviceCredential" },
53c44
<            "image": "{{resource.assets.container.docker.jenkins-353-21501}}",
---
>            "image": "{{resource.assets.container.docker.jenkins-354-21501}}",
diff 29/package.json 30/package.json
4c4
<   "version": "3.5.3-2.150.1",
---
>   "version": "3.5.4-2.150.1",
diff 29/resource.json 30/resource.json
10c10
<         "jenkins-353-21501": "mesosphere/jenkins:3.5.3-2.150.1"
---
>         "jenkins-354-21501": "mesosphere/jenkins:3.5.4-2.150.1"
```

**Comment by kvish** [comment]
@takirala closed

**Comment by kvish** [comment]
resolves: COPS-4629

**Pull request merged**
