### PR TITLE
Remove Kubernetes

### PR DESCRIPTION
**Pull request by jsancio**

### CODE REVIEW

**Comment by LiftedKilt** [comment]
@jsancio - why was kubernetes removed from universe? Is there a supported method for deploying kubernetes on DCOS still?

**Comment by jdef** [comment]
https://dcos-community.slack.com/messages/kubernetes/

**Comment by VincentSurelle** [comment]
@jdef You link can't be seen :/
So is there still a way to deploy Kubernetes on DCOS ?

**Comment by jdef** [comment]
k8s on dcos is no longer supported by universe packages. development effort
for the mesos framework has moved here:
https://github.com/kubernetes-incubator/kube-mesos-framework

**Pull request merged**
