### PR TITLE
Adding Ethereum v0.1.0

### PR DESCRIPTION
**Pull request by drewkerrigan**
Source and documentation available at https://github.com/iss-lab/dcos-ethereum

This package enables installation of an Ethereum (via Geth) network on DC/OS.

### CODE REVIEW

**Comment by vishnu2kmohan** [comment]
@drewkerrigan I kicked off all the TeamCity tests and they've all passed. 

I'll leave it to @ryadav88 and @mattj-io to review and merge.

**Comment by mattj-io** [comment]
@ryadav88 - I don't know enough about packages to review this code, although happy to test. Can you review please ?

**Comment by drewkerrigan** [comment]
Thank you @vishnu2kmohan @mattj-io @ryadav88, Looks like @guenter has already tweeted about this package, so hopefully we can get it merged soon :-)

**Comment by ryadav88** [comment]
@drewkerrigan can you create a basic documentation example by creating a PR against: https://github.com/dcos/examples. You can use the template from any other example there. 
This is also a requirement to add a new package to Universe. 
https://github.com/mesosphere/universe#submit-your-package

**Comment by mattj-io** [comment]
Can we also get a licenses section in package.json please :)

**Comment by drewkerrigan** [comment]
@mattj-io Licenses section added. @ryadav88 I've created https://github.com/dcos/examples/pull/385 - please let me know if there's anything else needed, thanks!

**Comment by vishnu2kmohan** [comment]
TC Tests were re-triggered and have passed. Should be good to merge. Thanks @drewkerrigan!

**Pull request merged**
