### PR TITLE
Fix template bug where node-count was used for seed count.

### PR DESCRIPTION
**Pull request by BenWhitehead**

### CODE REVIEW

**Comment by BenWhitehead** [comment]
@jsancio Please review

**Comment by BenWhitehead** [comment]
so fast!

**Comment by jsancio** [comment]
> so fast!

```
$ git grep seed-count
repo/packages/C/cassandra/0/config-sample.json:  "cassandra/seed-count": "2",
repo/packages/C/cassandra/0/config.json:    "cassandra/seed-count": {
```

:smile:

**Comment by BenWhitehead** [comment]
new Linter option. Make sure that all properties that are declared are read at some point.

**Comment by jsancio** [comment]
Done: #76

**Pull request merged**
