### PR TITLE
Add consul 0.1.0-1.4.0

### PR DESCRIPTION
**Pull request by swoehrl-mw**
https://github.com/MaibornWolff/dcos-consul
New framework for installing consul in HA mode. Based on consul 1.4.0.

Developed using https://github.com/mesosphere/dcosdev

### CODE REVIEW

**Comment by vishnu2kmohan** [comment]
@swoehrl-mw Kicked off the TC tests on your behalf.

**Comment by joerg84** [comment]
Build error above:  Will look into that later today, but just restarted the run for now.
```
[15:16:56][Step 2/2] Got status 403 Forbidden when fetching https://downloads.mesosphere.com/dcos-commons/artifacts/0.53.0/executor.zip, retrying...
[15:17:00][Step 2/2] Got status 403 Forbidden when fetching https://downloads.mesosphere.com/dcos-commons/artifacts/0.53.0/executor.zip, retrying...
[15:17:03][Step 2/2] dcos: error: Got status 403 Forbidden when fetching https://downloads.mesosphere.com/dcos-commons/artifacts/0.53.0/executor.zip, try --help
[15:17:03][Step 2/2] + [[ 1 != 0 ]]```

**Comment by vishnu2kmohan** [comment]
SDK 0.5x no longer requires `executor.zip` since we have switched to Mesos' Default Executor: see - https://github.com/mesosphere/dcos-commons/commit/62f7a5ab6ff17e8d7ccc62647c8b53e7ee655483

Ideally, please rebase on to SDK 0.54.3 (https://github.com/mesosphere/dcos-commons/tree/0.54.3)

**Comment by swoehrl-mw** [comment]
I have removed the executor.zip as indeed it is not used, was only in there as it is part of the template instantiated by dcosdev.
Unless there are strong arguments against using 0.53.0 I'd like to stick with that version for now to avoid retesting everything. But I will make a note to update the version for the next release.

**Review by joerg84 — APPROVED** [review]

**Comment by realmbgl** [comment]
looks good, thanks for the contribution Sebastian

**Pull request merged**
