### PR TITLE
Removed the Jenkins package.

### PR DESCRIPTION
**Pull request by ConnorDoyle**
- Fixes DCOS-1663.
- This package is moving to a new branch called `experimental`.

### CODE REVIEW

**Comment by air** [comment]
:+1:

**Comment by ConnorDoyle** [comment]
Go ahead @air... click the button :)

**Comment by ryanmaclean** [comment]
*sadface* - https://mesosphere.com/learn/
One of those fancy animations promised Jenkins, luckily I found this page!

**Comment by adam-mesos** [comment]
@ryanmaclean See also https://github.com/mesosphere/multiverse/tree/master/repo/packages/J/jenkins/0
The multiverse repo holds packages that aren't quite up to snuff. Jenkins, for instance, does not gracefully handle scheduler failover.

**Pull request merged**
