### PR TITLE
Update Minio to latest stable release

### PR DESCRIPTION
**Pull request by nitisht**

### CODE REVIEW

**Comment by nitisht** [comment]
cc @krisis @harshavardhana

**Comment by ryadav88** [comment]
@nitisht the builds fail because the screenshots here return a 404 https://github.com/mesosphere/universe/pull/1892/files#diff-18a9222bfd42a5d6dc5b3acaba885813R6

**Comment by ryadav88** [comment]
@nitisht any update here?

**Comment by nitisht** [comment]
I have not yet been able to get back to this, will do in a couple of days @ryadav88

**Comment by nitisht** [comment]
@ryadav88 I removed the screenshots section for now, but I still see it fails. Is it possible to access failure logs without login to TeamCity

**Comment by ryadav88** [comment]
it was an authorization failure. I reran the tests.

**Comment by nitisht** [comment]
Thanks @ryadav88

**Pull request merged**
