### PR TITLE
Add licenses for dcos-core-cli

### PR DESCRIPTION
**Pull request by bamarni**

### CODE REVIEW

**Review by mattj-io — COMMENTED** [review]
LGTM

**Review by armandgrillet — APPROVED** [review]

**Comment by mattj-io** [comment]
Based on our Slack conversation, am I right in thinking that each release is basically copying the package.json from the previous release ? ie. if these are fixed then everything going forward will have license attribution ?

**Review by mattj-io — APPROVED** [review]

**Comment by bamarni** [comment]
@mattj-io : correct, I've also added it for dcos-enterprise-cli, so next releases will also have it.

**Comment by bamarni** [comment]
@mattj-io : I'm getting errors like `dcos: error: The build definition /usr/src/github.com/mesosphere/target/dcos-enterprise-cli-1.0.7.json already exists, try --help`, I'm not sure it is supported to overwrite old releases as it might mess around with checksums of released artifacts, @takirala do you have more info on this?

**Pull request merged**
