### PR TITLE
Update Marathon to 0.9.0-RC3

### PR DESCRIPTION
**Pull request by kolloch**
Attention: Wait for the docker build to actually finish and test this. I haven't tested this yet!

### CODE REVIEW

**Comment by kolloch** [comment]
I changed it to a new directory.

It is still untested and I have not added any of the new command line arguments.

**Comment by kolloch** [comment]
Ok, updated it again. Added package.json and config.json. They are both copies of the files in the 0 directory. I just changed the version number in package.json.

**Comment by kolloch** [comment]
Now I also updated the index.json via running `./scripts/build.sh`

**Comment by aquamatthias** [comment]
Connor: "Ship that shit"

**Pull request merged**
