### PR TITLE
Updating to latest Kafka Executor (version 1.18)

### PR DESCRIPTION
**Pull request by dbtucker**
This executor adds some useful placement capabilities along with JMX and statistics monitoriing.

### CODE REVIEW

**Comment by joerg84** [comment]
@triclambert could you or someone from your team review this?

**Comment by gabrielhartmann** [comment]
@dbtucker: LGTM.  I gave it a try on a DC/OS 1.9 cluster, all seems fine.  Do you have permissions to merge or would you like me too?  Thanks for the ping @joerg84.

**Comment by dbtucker** [comment]
Thanks, @gabrielhartmann    It probably makes sense to update the packages to require DC/OS 1.8 or later with the next version (Confluent 3.2).   There were some features around the config file structure that changed at 1.8, and it's probably as good a time as any to cross the chasm.

**Comment by gabrielhartmann** [comment]
@dbtucker:  Makes sense to me.  Did you want to merge this?

**Comment by dbtucker** [comment]
Yes, please do merge this.   There was a prospect looking at rack placement control for the Kafka brokers that is interested in this update.

**Pull request merged**
