### PR TITLE
Predator 1.0.0

### PR DESCRIPTION
**Pull request by NivLipetz**

### CODE REVIEW

**Comment by mattj-io** [comment]
@ryadav88

**Comment by ryadav88** [comment]
I re-ran the tests. @NivLipetz can you also add a getting started example documentation for this package here: https://github.com/dcos/examples

**Comment by vishnu2kmohan** [comment]
@NivLipetz @ryadav88 FYI - I re-ran the tests they've all passed.

**Review by vishnu2kmohan — APPROVED** [review]
TeamCity Tests have passed, conditional approval modulo documentation.

**Comment by NivLipetz** [comment]
@ryadav88 added examples to the dcos/examples repo. PR found here: https://github.com/dcos/examples/pull/392

**Review by ryadav88 — APPROVED** [review]

**Pull request merged**
