### PR TITLE
Update cassandra package version to 0.2.0-1.

### PR DESCRIPTION
**Pull request by BenWhitehead**
New marathon.json and config definition to support multi datacenter features.

### CODE REVIEW

**Comment by kensipe** [comment]
LGTM... could you rebase?  and I'll merge if you like

**Comment by kensipe** [comment]
oops... I spoke too soon.   I am testing on dcos... and no joy.   The marathon deployment failed multiple times.

**Comment by kensipe** [comment]
@BenWhitehead 

stderr:

```
/opt/mesosphere/packages/mesos--5018921cbb873aea2a0db00a407d77a8de419f63/libexec/mesos/mesos-fetcher: /lib64/libcurl.so.4: no version information available (required by /opt/mesosphere/packages/mesos--5018921cbb873aea2a0db00a407d77a8de419f63/libexec/mesos/mesos-fetcher)
I0810 19:16:58.708612  4080 logging.cpp:172] INFO level logging started!
I0810 19:16:58.710204  4080 fetcher.cpp:214] Fetching URI 'https://downloads.mesosphere.io/cassandra-mesos/artifacts/0.2.0-1/cassandra-mesos-0.2.0-1.tar.gz'
I0810 19:16:58.710227  4080 fetcher.cpp:125] Fetching URI 'https://downloads.mesosphere.io/cassandra-mesos/artifacts/0.2.0-1/cassandra-mesos-0.2.0-1.tar.gz' with os::net
I0810 19:16:58.710238  4080 fetcher.cpp:135] Downloading 'https://downloads.mesosphere.io/cassandra-mesos/artifacts/0.2.0-1/cassandra-mesos-0.2.0-1.tar.gz' to '/var/lib/mesos/slave/slaves/20150810-142548-1829109770-5050-1297-S5/frameworks/20150810-142548-1829109770-5050-1297-0000/executors/cassandra_dcos.5f0571af-3f94-11e5-9d3c-56847afe9799/runs/90b782fc-26c5-4b96-be34-bbd82c6e590d/cassandra-mesos-0.2.0-1.tar.gz'
E0810 19:16:59.079552  4080 fetcher.cpp:141] Error downloading resource, received HTTP/FTP return code 503
Failed to fetch: https://downloads.mesosphere.io/cassandra-mesos/artifacts/0.2.0-1/cassandra-mesos-0.2.0-1.tar.gz
Failed to synchronize with slave (it's probably exited)
```

**Comment by BenWhitehead** [comment]
The artifact is definitely there. Looks like aws was having some errors:

>12:28 PM PDT Between 12:03 PM to 12:19 PM PDT we experienced elevated errors for requests made to Amazon S3 in the US-STANDARD Region. The issue has been resolved and the service is operating normally.

http://status.aws.amazon.com/

**Comment by kensipe** [comment]
tested again... LGTM... @BenWhitehead you ready for a merge?

**Comment by BenWhitehead** [comment]
testing right now, will merge when complete.

**Comment by BenWhitehead** [comment]
thanks for the review

**Comment by kensipe** [comment]
roger

**Pull request merged**
