### PR TITLE
Helloworld

### PR DESCRIPTION
**Pull request by mgummelt**
remove docker so we can run this in TC (there were docker on docker issues)

### CODE REVIEW

**Comment by mgummelt** [comment]
I tested on DCOS

**Comment by ConnorDoyle** [comment]
:ship: it.

**Comment by cmaloney** [comment]
This relies on the host python3 in DCOS, which is strictly against the Service guidelines. Please don't do that! The python is not guaranteed to be there and will likely move without notice).

**Comment by mgummelt** [comment]
can you link me to the service guidelines?

**Comment by cmaloney** [comment]
Not shared publicly at the moment I don't think. Sending to you privately.

**Pull request merged**
