### PR TITLE
removing cli for hdfs and cassandra

### PR DESCRIPTION
**Pull request by kensipe**

### CODE REVIEW

**Comment by jdef** [comment]
where is the CLI moving to? do we have a new pattern that we're adopting
for integrating CLI into packages?

**Comment by jsancio** [comment]
Please create a pr against version-2.x also.

**Comment by kensipe** [comment]
@jsancio sure thing... should it be in the v2 format?  or can I use this existing format which can be updated later?

**Comment by kensipe** [comment]
@jdef I'm not sure... I haven't been including in the loop.   The CLI are broken or useless at this point and we want to remove them.   We will have a `good` CLI replacement in the near future.

**Comment by kensipe** [comment]
@jsancio forget my last comment regarding v2.  I can use the existing work you did with hdfs to create a v2 version without the cli... I will have it shortly.

**Comment by BenWhitehead** [comment]
please retarget this PR at branch `version-2.x`

**Comment by kensipe** [comment]
removed from `version-2.x` already in place... closing this PR

**Pull request closed without merging**
