### PR TITLE
Add support for Confluent 3.2.0  (February 2017 release)

### PR DESCRIPTION
**Pull request by dbtucker**
Minor updates to versions of package artifacts.

### CODE REVIEW

**Comment by gabrielhartmann** [comment]
@dbtucker:  It would be really helpful for review if these PRs contained diffs in them like [the automated commits generated for the generic Kafka service](https://github.com/mesosphere/universe/pull/976).  It's hard to review 1,800 lines meaningfully without manually diffing.

**Comment by dbtucker** [comment]
Happy to do so, Gabriel.   Is there a tool you can point me to that will generate that content ... or is it simply exhaustive git commands ?

**Comment by gabrielhartmann** [comment]
@dbtucker: We wrote [a python script which generates our Universe PRs](https://github.com/mesosphere/dcos-commons/blob/master/tools/release_builder.py).  Looks like it uses a library called `difflib`.  Maybe [here is the entry point](https://github.com/mesosphere/dcos-commons/blob/master/tools/release_builder.py#L218) for where we do diffing.  @nickbp would know better.

**Comment by gabrielhartmann** [comment]
@dbtucker:  In our CI build to release packages we issue the command like this:
`./tools/release_builder.py "${RELEASE_VERSION}" "${STUB_UNIVERSE_URL}" "${COMMIT_MESSAGE}"`

**Comment by dbtucker** [comment]
OK.  I'll try that for the next release.   Easy enough to get the git diffs here.

**confluent-kafka package diffs**
diff --git a/HEAD:./14/command.json b/HEAD:./13/command.json
index 1379fc4..644cd11 100644
--- a/HEAD:./14/command.json
+++ b/HEAD:./13/command.json
@@ -1,5 +1,5 @@
 {
   "pip": [
-    "https://downloads.mesosphere.com/kafka/assets/1.1.19-0.10.1.0/bin_wrapper-0.0.1-py2.py3-none-any.whl"
+    "https://downloads.mesosphere.com/kafka/assets/1.1.18-0.10.1.0/bin_wrapper-0.0.1-py2.py3-none-any.whl"
   ]
 }
diff --git a/HEAD:./14/marathon.json.mustache b/HEAD:./13/marathon.json.mustache
index 8d8d9f9..245734f 100644
--- a/HEAD:./14/marathon.json.mustache
+++ b/HEAD:./13/marathon.json.mustache
@@ -3,7 +3,7 @@
   "cpus": 1.0,
   "mem": 1230,
   "instances": 1,
-  "cmd": "export LD_LIBRARY_PATH=$MESOS_SANDBOX/libmesos-bundle/lib:$LD_LIBRARY_PATH && export MESOS_NATIVE_JAVA_LIBRARY=$(ls $MESOS_SANDBOX/libmesos-bundle/lib/libmesos-*.so) && export PATH=$(ls -d $MESOS_SANDBOX/jre*/bin):$PATH && ./scheduler/bin/kafka-scheduler server ./scheduler/conf/scheduler.yml",
+  "cmd": "export PATH=$(ls -d $MESOS_SANDBOX/jre*/bin):$PATH && ./scheduler/bin/kafka-scheduler server ./scheduler/conf/scheduler.yml",
   "labels": {
     "DCOS_PACKAGE_FRAMEWORK_NAME": "{{service.name}}",
     "DCOS_MIGRATION_API_VERSION": "v1",
@@ -15,7 +15,6 @@
   },
   "env": {
     "LD_LIBRARY_PATH": "/opt/mesosphere/lib",
-    "JAVA_HOME":"./jre1.8.0_121",
     "FRAMEWORK_NAME": "{{service.name}}",
     "FRAMEWORK_PRINCIPAL": "{{service.principal}}",
     "USER": "{{service.user}}",
@@ -47,7 +46,7 @@
     "BROKER_STATSD_HOST": "{{brokers.statsd.host}}",
     "BROKER_STATSD_PORT": "{{brokers.statsd.port}}",
     "DISK_TYPE": "{{brokers.disk_type}}",
-    "KAFKA_VER_NAME": "kafka_confluent-3.2.0",
+    "KAFKA_VER_NAME": "kafka_confluent-3.1.2",
     "KAFKA_URI": "{{resource.assets.uris.kafka_tgz}}",
     "OVERRIDER_URI": "{{resource.assets.uris.overrider-zip}}",
     "EXECUTOR_URI": "{{resource.assets.uris.executor-zip}}",
@@ -142,8 +141,8 @@
     "KAFKA_OVERRIDE_COMPRESSION_TYPE": "{{kafka.compression_type}}"
     {{#service.secret_name}}
     ,"DCOS_SERVICE_ACCOUNT_CREDENTIAL": { "secret": "serviceCredential" },
-    "MESOS_MODULES": "{\"libraries\": [{\"file\": \"libdcos_security.so\", \"modules\": [{\"name\": \"com_mesosphere_dcos_ClassicRPCAuthenticatee\"}]}]}",
-    "MESOS_AUTHENTICATEE": "com_mesosphere_dcos_ClassicRPCAuthenticatee"
+    "MESOS_MODULES": "file:///opt/mesosphere/etc/mesos-scheduler-modules/dcos_authenticatee_module.json",
+    "MESOS_AUTHENTICATEE": "com_mesosphere_dcos_ClassicRPCAuthenticatee",
     {{/service.secret_name}}
   },
   {{#service.secret_name}}
@@ -156,8 +155,7 @@
   "uris": [
     "{{resource.assets.uris.jre-tar-gz}}",
     "{{resource.assets.uris.scheduler-zip}}",
-    "{{resource.assets.uris.kafka_tgz}}",
-    "{{resource.assets.uris.libmesos-bundle-tar-gz}}"
+    "{{resource.assets.uris.kafka_tgz}}"
   ],
   "healthChecks": [
     {
diff --git a/HEAD:./14/package.json b/HEAD:./13/package.json
index dc7c1a5..007e677 100644
--- a/HEAD:./14/package.json
+++ b/HEAD:./13/package.json
@@ -1,7 +1,7 @@
 {
   "packagingVersion": "3.0",
   "name": "confluent-kafka",
-  "version": "1.1.19-3.2.0",
+  "version": "1.1.18-3.1.2",
   "minDcosReleaseVersion": "1.7",
   "maintainer": "partner-support@confluent.io",
   "description": "Apache Kafka by Confluent\n\n\tDocumentation: https://www.confluent.io/whitepaper/deploying-confluent-platform-with-mesosphere",
diff --git a/HEAD:./14/resource.json b/HEAD:./13/resource.json
index a63ec4e..7d3c8d9 100644
--- a/HEAD:./14/resource.json
+++ b/HEAD:./13/resource.json
@@ -2,11 +2,10 @@
     "assets": {
         "uris": {
             "jre-tar-gz": "https://downloads.mesosphere.com/java/jre-8u121-linux-x64.tar.gz",
-            "kafka_tgz": "https://packages.confluent.io/archive/3.2/confluent-oss-3.2.0-mesos.tgz",
-            "scheduler-zip": "https://downloads.mesosphere.com/kafka/assets/1.1.19-0.10.1.0/scheduler.zip",
-            "executor-zip": "https://downloads.mesosphere.com/kafka/assets/1.1.19-0.10.1.0/executor.zip",
-            "overrider-zip": "https://downloads.mesosphere.com/kafka/assets/1.1.19-0.10.1.0/overrider.zip",
-            "libmesos-bundle-tar-gz": "https://downloads.mesosphere.com/libmesos-bundle/libmesos-bundle-1.9-argus-1.1.x-3.tar.gz"
+            "kafka_tgz": "https://packages.confluent.io/archive/3.1/confluent-oss-3.1.2-mesos.tgz",
+            "scheduler-zip": "https://downloads.mesosphere.com/kafka/assets/1.1.18-0.10.1.0/scheduler.zip",
+            "executor-zip": "https://downloads.mesosphere.com/kafka/assets/1.1.18-0.10.1.0/executor.zip",
+            "overrider-zip": "https://downloads.mesosphere.com/kafka/assets/1.1.18-0.10.1.0/overrider.zip"
         }
     },
     "images": {
@@ -18,23 +17,23 @@
         "binaries":{
             "darwin":{
                 "x86-64":{
-                    "contentHash":[ { "algo":"sha256", "value":"660f143852b6d3d2b0b2f787fab9e5e2927f4440502a89c9e1c08488cdacc34f" } ],
+                    "contentHash":[ { "algo":"sha256", "value":"9a3d9076133506ea325120d460d33ea0272951f074b363d72860dcef36279257" } ],
                     "kind":"executable",
-                    "url":"https://downloads.mesosphere.com/kafka/assets/1.1.19-0.10.1.0/dcos-kafka-darwin"
+                    "url":"https://downloads.mesosphere.com/kafka/assets/1.1.18-0.10.1.0/dcos-kafka-darwin"
                 }
             },
             "linux":{
                 "x86-64":{
-                    "contentHash":[ { "algo":"sha256", "value":"0b26409c9760fd4d75fca1114d01f25ec069147d578d6f337c88424ebc64c808" } ],
+                    "contentHash":[ { "algo":"sha256", "value":"6eb3725a793d7f21c9296f45685005833fb6ee07ca084bd1be50c26db01c508c" } ],
                     "kind":"executable",
-                    "url":"https://downloads.mesosphere.com/kafka/assets/1.1.19-0.10.1.0/dcos-kafka-linux"
+                    "url":"https://downloads.mesosphere.com/kafka/assets/1.1.18-0.10.1.0/dcos-kafka-linux"
                 }
             },
             "windows":{
                 "x86-64":{
-                    "contentHash":[ { "algo":"sha256", "value":"60d6f802412b94833cf8db217af162e7dc35c0f5e0a1eb4b587268c361500c3b" } ],
+                    "contentHash":[ { "algo":"sha256", "value":"229b1b4f65e534a610769eabd6da9886a0a041afd735a336377f4cb0579008f5" } ],
                     "kind":"executable",
-                    "url":"https://downloads.mesosphere.com/kafka/assets/1.1.19-0.10.1.0/dcos-kafka.exe"
+                    "url":"https://downloads.mesosphere.com/kafka/assets/1.1.18-0.10.1.0/dcos-kafka.exe"
                 }
             }
         }

**Comment by dbtucker** [comment]
And diffs for the marathon components (far less complex)

**confluent-connect**
diff --git a/HEAD:./5/package.json b/HEAD:./4/package.json
index 772e4db..0bc748f 100644
--- a/HEAD:./5/package.json
+++ b/HEAD:./4/package.json
@@ -1,9 +1,9 @@
 {
   "packagingVersion": "3.0",
   "name": "confluent-connect",
-  "version": "0.9.8-3.2.0",
+  "version": "0.9.6-3.1.2",
   "scm": "https://github.com/confluentinc/kafka",
-  "description": "Confluent Connect worker\n\n\tDocumentation: http://docs.confluent.io/3.2.0/connect/managing.html",
+  "description": "Confluent Connect worker\n\n\tDocumentation: http://docs.confluent.io/3.1.2/connect/managing.html",
   "maintainer": "partner-support@confluent.io",
   "tags": ["kafka", "confluent", "connect"],
   "preInstallNotes": "Preparing to install confluent-connect",
diff --git a/HEAD:./5/resource.json b/HEAD:./4/resource.json
index 97afe1b..7ae3082 100644
--- a/HEAD:./5/resource.json
+++ b/HEAD:./4/resource.json
@@ -2,7 +2,7 @@
   "assets": {
     "container": {
       "docker": {
-        "image": "confluentinc/cp-kafka-connect:3.2.0"
+        "image": "confluentinc/cp-kafka-connect:3.1.2"
       }
     }
   },


**confluent-control-center**
diff --git a/HEAD:./5/package.json b/HEAD:./4/package.json
index 2ce77a6..158b74c 100644
--- a/HEAD:./5/package.json
+++ b/HEAD:./4/package.json
@@ -1,9 +1,9 @@
 {
   "packagingVersion": "3.0",
   "name": "confluent-control-center",
-  "version": "0.9.8-3.2.0",
+  "version": "0.9.6-3.1.2",
   "scm": "https://github.com/confluentinc/control-center",
-  "description": "Confluent Control Center service\n\n\tDocumentation: http://docs.confluent.io/3.2.0/control-center/docs/userguide.html\n\tDC/OS Specifics: https://www.confluent.io/whitepaper/deploying-confluent-platform-with-mesosphere",
+  "description": "Confluent Control Center service\n\n\tDocumentation: http://docs.confluent.io/3.1.2/control-center/docs/userguide.html\n\tDC/OS Specifics: https://www.confluent.io/whitepaper/deploying-confluent-platform-with-mesosphere",
   "maintainer": "partner-support@confluent.io",
   "tags": ["kafka", "confluent", "control", "center"],
   "preInstallNotes": "Preparing to install confluent-control-center",
diff --git a/HEAD:./5/resource.json b/HEAD:./4/resource.json
index 247637b..3490d78 100644
--- a/HEAD:./5/resource.json
+++ b/HEAD:./4/resource.json
@@ -2,7 +2,7 @@
   "assets": {
     "container": {
       "docker": {
-        "image": "confluentinc/cp-enterprise-control-center:3.2.0"
+        "image": "confluentinc/cp-enterprise-control-center:3.1.2"
       }
     }
   },


**confluent-replicator**
diff --git a/HEAD:./2/package.json b/HEAD:./1/package.json
index 8d5f7d9..db41ab0 100644
--- a/HEAD:./2/package.json
+++ b/HEAD:./1/package.json
@@ -1,9 +1,9 @@
 {
   "packagingVersion": "3.0",
   "name": "confluent-replicator",
-  "version": "0.9.8-3.2.0",
+  "version": "0.9.6-3.1.2",
   "scm": "https://github.com/confluentinc/kafka",
-  "description": "Confluent Enterprise Replicator for multi-data center synchronization of topic data\n\n\tDocumentation: http://docs.confluent.io/3.2.0/connect/connect-replicator/docs/index.html",
+  "description": "Confluent Enterprise Replicator for multi-data center synchronization of topic data\n\n\tDocumentation: http://docs.confluent.io/3.1.2/connect/connect-replicator/docs/index.html",
   "maintainer": "partner-support@confluent.io",
   "tags": ["kafka", "confluent", "connect", "replicator"],
   "preInstallNotes": "Preparing to install Replicator service",
diff --git a/HEAD:./2/resource.json b/HEAD:./1/resource.json
index 5d1dfff..17e3917 100644
--- a/HEAD:./2/resource.json
+++ b/HEAD:./1/resource.json
@@ -2,7 +2,7 @@
   "assets": {
     "container": {
       "docker": {
-        "image": "confluentinc/cp-enterprise-replicator:3.2.0"
+        "image": "confluentinc/cp-enterprise-replicator:3.1.2"
       }
     }
   },


**confluent-rest-proxy**
diff --git a/HEAD:./5/package.json b/HEAD:./4/package.json
index fa97105..b9a37c1 100644
--- a/HEAD:./5/package.json
+++ b/HEAD:./4/package.json
@@ -1,9 +1,9 @@
 {
   "packagingVersion": "3.0",
   "name": "confluent-rest-proxy",
-  "version": "0.9.8-3.2.0",
+  "version": "0.9.6-3.1.2",
   "scm": "https://github.com/confluentinc/kafka-rest",
-  "description": "Confluent REST Proxy service\n\n\tDocumentation: http://docs.confluent.io/3.2.0/kafka-rest/docs/api.html",
+  "description": "Confluent REST Proxy service\n\n\tDocumentation: http://docs.confluent.io/3.1.2/kafka-rest/docs/api.html",
   "maintainer": "partner-support@confluent.io",
   "tags": ["kafka", "confluent", "proxy", "rest"],
   "preInstallNotes": "Preparing to install confluent-rest-proxy",
diff --git a/HEAD:./5/resource.json b/HEAD:./4/resource.json
index f12aa50..af2b796 100644
--- a/HEAD:./5/resource.json
+++ b/HEAD:./4/resource.json
@@ -2,7 +2,7 @@
   "assets": {
     "container": {
       "docker": {
-        "image": "confluentinc/cp-kafka-rest:3.2.0"
+        "image": "confluentinc/cp-kafka-rest:3.1.2"
       }
     }
   },


**confluent-schema-registry**
diff --git a/HEAD:./5/package.json b/HEAD:./4/package.json
index 7e970be..64a263e 100644
--- a/HEAD:./5/package.json
+++ b/HEAD:./4/package.json
@@ -1,9 +1,9 @@
 {
   "packagingVersion": "3.0",
   "name": "confluent-schema-registry",
-  "version": "0.9.8-3.2.0",
+  "version": "0.9.6-3.1.2",
   "scm": "https://github.com/confluentinc/schema-registry",
-  "description": "Confluent Schema Registry service\n\n\tDocumentation: http://docs.confluent.io/3.2.0/schema-registry/docs/intro.html",
+  "description": "Confluent Schema Registry service\n\n\tDocumentation: http://docs.confluent.io/3.1.2/schema-registry/docs/intro.html",
   "maintainer": "partner-support@confluent.io",
   "tags": ["kafka", "confluent", "schema", "registry"],
   "preInstallNotes": "Preparing to install confluent-schema-registry",
diff --git a/HEAD:./5/resource.json b/HEAD:./4/resource.json
index bc9c4a7..aa74113 100644
--- a/HEAD:./5/resource.json
+++ b/HEAD:./4/resource.json
@@ -2,7 +2,7 @@
   "assets": {
     "container": {
       "docker": {
-        "image": "confluentinc/cp-schema-registry:3.2.0"
+        "image": "confluentinc/cp-schema-registry:3.1.2"
       }
     }
   },

**Comment by gabrielhartmann** [comment]
@dbtucker:  Thanks for the diff.  It looks like the package version is changing in an unexpected way (to me).

```
-  "version": "0.9.8-3.2.0",
+  "version": "0.9.6-3.1.2",
```

Should the "framework version" be headed backwards?

**Comment by dbtucker** [comment]
Yes, was playing around with the diff's and they wound up in the wrong order.   I'll fix it next time.

Please do merge the changes.   And thanks again for quick turnaround on this !

**Pull request merged**
