### PR TITLE
bumping universe release for marathon 1.5.0

### PR DESCRIPTION
**Pull request by kensipe**
Unlike previous minor version updates, this release will be tough to compare.  The https://github.com/mesosphere/marathon-stuff/tree/master/universe-creator tool was used to create the latest version of files.    
Tool updates: https://github.com/mesosphere/marathon-stuff/pull/20/files
include: 
* flag change from `max_tasks_per_offer` => `max_instances_per_offer `
* dcos version updated to `1.10`

The version from generation was changed from snapshot to `v1.5.0` for universe package version and for the marathon docker version.

### CODE REVIEW

**Comment by triclambert** [comment]
Does this not conflict with #1403?

**Comment by kensipe** [comment]
depends who lands first :) .  I thought that landed already... we will have to update this!  thanks!

**Comment by ichernetsky** [comment]
@triclambert, it does. Please merge #1403, and I will update this one afterwards.

**Review by ichernetsky — APPROVED** [review]

**Comment by kensipe** [comment]
as the original creator I can't approve... however I approve!  the changes Ivan made!

**Pull request merged**
