### PR TITLE
Gitlab 9 1 0 version update

### PR DESCRIPTION
**Pull request by twk3**
This update adds the features introduced in GitLab 9.1 

 - Service Desk (EE only)
 - Canary Deployments (EE only)
 - Burndown Charts (EE only)
 - Protected Tags
 - Discussions in Merge Requests and Issues
 - Microsoft Teams Integration
 - Easier File Templates
 - Auto-cancel Redundant Pipelines
 - Scheduled Pipelines Triggers
 - Improved Support for Jobs with Large Log Sizes

See https://about.gitlab.com/2017/04/22/gitlab-9-1-released/ for more changes and features.

This upgrade contains the security fixes included in  9.0.2

 - Changing a subgroup's path breaks links to files uploaded in projects within that subgroup
 - Private group name disclosure via nested groups parent_id in new/update

See https://about.gitlab.com/2017/03/29/gitlab-9-dot-0-dot-2-released/ for more information.

This update includes several bug fixes for regressions. Details on these bug fixes can be found here:
https://about.gitlab.com/2017/03/28/gitlab-9-dot-0-dot-1-released/
https://about.gitlab.com/2017/04/05/gitlab-9-dot-0-dot-3-released/
https://about.gitlab.com/2017/04/10/gitlab-9-dot-0-dot-5-released/
https://about.gitlab.com/2017/04/21/gitlab-9-dot-0-dot-6-released/

### CODE REVIEW

**Comment by twk3** [comment]
Tested the CE and EE install using a single-node instance. Tested an upgrade from the previous version to the new version on EE.

Confirmed registry, git over ssh, and git over http were all working.

cc\ @ssk2

**Comment by ryadav88** [comment]
@twk3 please update the Gitlab example here to reflect any changes: https://github.com/dcos/examples

**Comment by twk3** [comment]
@ryadav88 I've added an issue on our side to look at updating the example https://gitlab.com/gitlab-org/omnibus-gitlab/issues/2274

**Comment by twk3** [comment]
@ryadav88 is there anything else needed here for the version bump to go in?

**Comment by ryadav88** [comment]
@twk3 do we have a PR for `examples` repo?

**Comment by twk3** [comment]
@ryadav88 no we haven't scheduled anyone to work on it yet. Is this PR waiting on that work?

**Comment by ryadav88** [comment]
Yes, adding new examples or updating existing examples for Universe packages is now part of guidelines to submit a PR to Universe. 
https://github.com/mesosphere/universe#submit-your-package

**Comment by ryadav88** [comment]
@twk3 any update here?

**Comment by lambertjosh** [comment]
It looks like validation has been completed and examples have been updated. Is it possible to have these two reviewed so we can close this out?

**Comment by ryadav88** [comment]
@lambertjosh thanks for the update. I'll review them

**Pull request merged**
