### PR TITLE
Fix mongodb licenses

### PR DESCRIPTION
**Pull request by mattj-io**

### CODE REVIEW

**Review by ryadav88 — CHANGES_REQUESTED** [review]
the url should be https://github.com/percona/percona-server-mongodb/blob/master/LICENSE-Community.txt

**Comment by mattj-io** [comment]
Updated license URL

**Comment by ryadav88** [comment]
@mattj-io I don't see the updated Percona license in the PR.

**Comment by mattj-io** [comment]
my bad - repushing

**Review by ryadav88 — APPROVED** [review]

**Pull request merged**
